### ISSUE TITLE
Backend container doesnt start with latest container, ModuleNotFoundError: No module named 'pycocotools'

### ISSUE THREAD

**Issue by nowheretobefound** [LibrePhotos/librephotos#1036]
Use SECRET_KEY from env
Traceback (most recent call last):
  File "/code/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/local/lib/python3.11/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.11/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.11/dist-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/code/api/models/album_auto.py", line 6, in <module>
    from api.models.person import Person
  File "/code/api/models/person.py", line 8, in <module>
    from api.models.photo import Photo
  File "/code/api/models/photo.py", line 21, in <module>
    from api.im2txt.sample import im2txt
  File "/code/api/im2txt/sample.py", line 23, in <module>
    vocab = pickle.load(f)
            ^^^^^^^^^^^^^^
  File "/code/api/im2txt/build_vocab.py", line 5, in <module>
    from pycocotools.coco import COCO
ModuleNotFoundError: No module named 'pycocotools'

**Comment by derneuere** [comment]
I pushed a fix for this error :) Please pull the backend image again.
