### ISSUE TITLE
Dlib was compiled to use SSE41 instructions, but these aren't available on your machine.,

### ISSUE THREAD

**Issue by JasonLiuLiuLiuLiu** [LibrePhotos/librephotos#117]
Hello everyone, I installed this on my nas with docker. The CPU of my nas is intel G5420. According to ark.intel.com, the instruction set extension supported by this CPU is Intel®SSE4.1 and Intel®SSE4. 2. Therefore, SSE41 should be supported, but it throws the following exception. Can someone take a look?

thanks in advance

```
 * Restarting nginx nginx,
   ...done.,
Dlib was compiled to use SSE41 instructions, but these aren't available on your machine.,
Traceback (most recent call last):,
  File "manage.py", line 22, in <module>,
    execute_from_command_line(sys.argv),
  File "/miniconda/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line,
    utility.execute(),
  File "/miniconda/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute,
    django.setup(),
  File "/miniconda/lib/python3.8/site-packages/django/__init__.py", line 24, in setup,
    apps.populate(settings.INSTALLED_APPS),
  File "/miniconda/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate,
    app_config.import_models(),
  File "/miniconda/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models,
    self.models_module = import_module(models_module_name),
  File "/miniconda/lib/python3.8/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/code/api/models.py", line 44, in <module>,
    im2vec = Im2Vec(cuda=False),
  File "/code/api/im2vec.py", line 20, in __init__,
    self.model, self.extraction_layer = self._get_model_and_layer(model, layer),
  File "/code/api/im2vec.py", line 66, in _get_model_and_layer,
    model = models.resnet152(pretrained=True),
  File "/miniconda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 288, in resnet152,
    return _resnet('resnet152', Bottleneck, [3, 8, 36, 3], pretrained, progress,,
  File "/miniconda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 226, in _resnet,
    state_dict = load_state_dict_from_url(model_urls[arch],,
  File "/miniconda/lib/python3.8/site-packages/torch/hub.py", line 559, in load_state_dict_from_url,
    return torch.load(cached_file, map_location=map_location),
  File "/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 595, in load,
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args),
  File "/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load,
    magic_number = pickle_module.load(f, **pickle_load_args),
_pickle.UnpicklingError: unpickling stack underflow,
,
If you suspect this is an IPython 7.19.0 bug, please report it at:,
    https://github.com/ipython/ipython/issues,
or send an email to the mailing list at ipython-dev@python.org,
,
You can print a more detailed traceback right now with "%tb", or use "%debug",
to interactively debug it.,
,
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:,
    %config Application.verbose_crash=True,
,
Dlib was compiled to use SSE41 instructions, but these aren't available on your machine.,
```

**Comment by derneuere** [comment]
I have added a parameter to disable sse4 instructions. The build should be ready in a hour or so. Could you please do a docker-compose down, docker-compose pull and docker-compose up, to try if it works then?

**Comment by JasonLiuLiuLiuLiu** [comment]
it worked, thanks for you solved this issue so quickly.
