### ISSUE TITLE
Directory with special characters throws exceptions

### ISSUE THREAD

**Issue by turnbeutelvergesser** [LibrePhotos/librephotos#125]
I can login as amin an enable sign on, but then I get:
```
Creating network "librephotos_default" with the default driver
Creating librephotos-redis    ... done
Creating librephotos-proxy    ... done
Creating librephotos-db       ... done
Creating librephotos-frontend ... done
Creating librephotos-backend  ... done
Attaching to librephotos-redis, librephotos-frontend, librephotos-proxy, librephotos-db, librephotos-backend
librephotos-db       | 
librephotos-db       | PostgreSQL Database directory appears to contain a database; Skipping initialization
librephotos-db       | 
librephotos-frontend | serving frontend
librephotos-frontend | ERROR: Cannot copy to clipboard: Command failed: xsel --clipboard --input
librephotos-frontend | xsel: Can't open display: (null)
librephotos-frontend | : Inappropriate ioctl for device
librephotos-frontend | 
librephotos-frontend | 
librephotos-frontend | 
librephotos-frontend |    ┌────────────────────────────────────────────────┐
librephotos-frontend |    │                                                │
librephotos-frontend |    │   Serving!                                     │
librephotos-frontend |    │                                                │
librephotos-frontend |    │   - Local:            http://localhost:3000    │
librephotos-frontend |    │   - On Your Network:  http://172.19.0.3:3000   │
librephotos-frontend |    │                                                │
librephotos-frontend |    └────────────────────────────────────────────────┘
librephotos-frontend | 
librephotos-proxy    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
librephotos-proxy    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
librephotos-proxy    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
librephotos-proxy    | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
librephotos-proxy    | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
librephotos-proxy    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
librephotos-proxy    | /docker-entrypoint.sh: Configuration complete; ready for start up
librephotos-proxy    | 2021/01/11 21:18:53 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/nginx.conf:22
librephotos-proxy    | nginx: [emerg] host not found in upstream "backend" in /etc/nginx/nginx.conf:22
librephotos-db       | 2021-01-11 21:18:54.829 UTC [1] LOG:  starting PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
librephotos-db       | 2021-01-11 21:18:54.829 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
librephotos-db       | 2021-01-11 21:18:54.829 UTC [1] LOG:  listening on IPv6 address "::", port 5432
librephotos-redis    | 1:C 11 Jan 2021 21:18:51.403 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
librephotos-redis    | 1:C 11 Jan 2021 21:18:51.403 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
librephotos-redis    | 1:C 11 Jan 2021 21:18:51.403 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
librephotos-redis    | 1:M 11 Jan 2021 21:18:51.405 * Running mode=standalone, port=6379.
librephotos-redis    | 1:M 11 Jan 2021 21:18:51.405 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
librephotos-redis    | 1:M 11 Jan 2021 21:18:51.405 # Server initialized
librephotos-redis    | 1:M 11 Jan 2021 21:18:51.405 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
librephotos-db       | 2021-01-11 21:18:54.830 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
librephotos-db       | 2021-01-11 21:18:54.832 UTC [26] LOG:  database system was shut down at 2021-01-11 21:18:27 UTC
librephotos-redis    | 1:M 11 Jan 2021 21:18:51.405 * Ready to accept connections
librephotos-db       | 2021-01-11 21:18:54.855 UTC [1] LOG:  database system is ready to accept connections
librephotos-backend  |  * Restarting nginx nginx
librephotos-backend  |    ...done.
librephotos-backend  | admin
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_logentry_remove_auto_add
librephotos-backend  |  [X] 0003_logentry_add_action_flag_choices
librephotos-backend  | api
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_add_confidence
librephotos-backend  |  [X] 0003_remove_unused_thumbs
librephotos-backend  | auth
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_alter_permission_name_max_length
librephotos-backend  |  [X] 0003_alter_user_email_max_length
librephotos-backend  |  [X] 0004_alter_user_username_opts
librephotos-backend  |  [X] 0005_alter_user_last_login_null
librephotos-backend  |  [X] 0006_require_contenttypes_0002
librephotos-backend  |  [X] 0007_alter_validators_add_error_messages
librephotos-backend  |  [X] 0008_alter_user_username_max_length
librephotos-backend  |  [X] 0009_alter_user_last_name_max_length
librephotos-backend  |  [X] 0010_alter_group_name_max_length
librephotos-backend  |  [X] 0011_update_proxy_permissions
librephotos-backend  | contenttypes
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_remove_content_type_name
librephotos-backend  | database
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_auto_20190129_2304
librephotos-backend  | sessions
librephotos-backend  |  [X] 0001_initial
librephotos-backend  | Operations to perform:
librephotos-backend  |   Apply all migrations: admin, api, auth, contenttypes, database, sessions
librephotos-backend  | Running migrations:
librephotos-backend  |   No migrations to apply.
librephotos-backend  |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
librephotos-backend  |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
librephotos-backend  | admin
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_logentry_remove_auto_add
librephotos-backend  |  [X] 0003_logentry_add_action_flag_choices
librephotos-backend  | api
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_add_confidence
librephotos-backend  |  [X] 0003_remove_unused_thumbs
librephotos-backend  | auth
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_alter_permission_name_max_length
librephotos-backend  |  [X] 0003_alter_user_email_max_length
librephotos-backend  |  [X] 0004_alter_user_username_opts
librephotos-backend  |  [X] 0005_alter_user_last_login_null
librephotos-backend  |  [X] 0006_require_contenttypes_0002
librephotos-backend  |  [X] 0007_alter_validators_add_error_messages
librephotos-backend  |  [X] 0008_alter_user_username_max_length
librephotos-backend  |  [X] 0009_alter_user_last_name_max_length
librephotos-backend  |  [X] 0010_alter_group_name_max_length
librephotos-backend  |  [X] 0011_update_proxy_permissions
librephotos-backend  | contenttypes
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_remove_content_type_name
librephotos-backend  | database
librephotos-backend  |  [X] 0001_initial
librephotos-backend  |  [X] 0002_auto_20190129_2304
librephotos-backend  | sessions
librephotos-backend  |  [X] 0001_initial
librephotos-backend  | 127.0.0.1 - - [2021-01-11 21:19:45] "POST /build/ HTTP/1.1" 200 139 0.003959
librephotos-backend  | 127.0.0.1 - - [2021-01-11 21:19:45] "POST /build/ HTTP/1.1" 200 139 0.000846
librephotos-backend  | Running backend server...
librephotos-backend  | [2021-01-11 21:19:56 +0000] [146] [INFO] Starting gunicorn 20.0.4
librephotos-backend  | [2021-01-11 21:19:56 +0000] [146] [INFO] Listening at: http://0.0.0.0:8001 (146)
librephotos-backend  | [2021-01-11 21:19:56 +0000] [146] [INFO] Using worker: gevent
librephotos-backend  | [2021-01-11 21:19:56 +0000] [150] [INFO] Booting worker with pid: 150
librephotos-backend  | [2021-01-11 21:19:56 +0000] [156] [INFO] Booting worker with pid: 156
librephotos-backend  | [2021-01-11 21:19:56 +0000] [157] [INFO] Booting worker with pid: 157
librephotos-backend  | [2021-01-11 21:19:56 +0000] [158] [INFO] Booting worker with pid: 158
librephotos-backend  | 21:20:15 Worker rq:worker:5f7b9aa01b2847a9995fa7d1b205af7e: started, version 1.6.1
librephotos-backend  | 21:20:15 Subscribing to channel rq:pubsub:5f7b9aa01b2847a9995fa7d1b205af7e
librephotos-backend  | 21:20:15 *** Listening on default...
librephotos-backend  | 21:20:15 Cleaning registries for queue: default
librephotos-backend  | Not Found: /api/jobs/
librephotos-backend  | [2021-01-11 21:20:31 +0000] [158] [ERROR] Error handling request /api/dirtree/
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
librephotos-backend  |     response = self.process_exception_by_middleware(e, request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
librephotos-backend  |     response = response.render()
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/template/response.py", line 105, in render
librephotos-backend  |     self.content = self.rendered_content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
librephotos-backend  |     ret = renderer.render(self.data, accepted_media_type, context)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/renderers.py", line 110, in render
librephotos-backend  |     return ret.encode()
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 5896: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/code/api/middleware.py", line 9, in __call__
librephotos-backend  |     response = self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
librephotos-backend  |     response = response or self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | 
librephotos-backend  | During handling of the above exception, another exception occurred:
librephotos-backend  | 
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 55, in handle
librephotos-backend  |     self.handle_request(listener_name, req, client, addr)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
librephotos-backend  |     super().handle_request(listener_name, req, sock, addr)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
librephotos-backend  |     respiter = self.wsgi(environ, resp.start_response)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
librephotos-backend  |     response = self.get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
librephotos-backend  |     response = self._middleware_chain(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
librephotos-backend  |     response = response_for_exception(request, exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
librephotos-backend  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
librephotos-backend  |     return debug.technical_500_response(request, *exc_info)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 95, in technical_500_response
librephotos-backend  |     return HttpResponse(html, status=status_code, content_type='text/html')
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 292, in __init__
librephotos-backend  |     self.content = content
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 322, in content
librephotos-backend  |     content = self.make_bytes(value)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/http/response.py", line 235, in make_bytes
librephotos-backend  |     return bytes(value.encode(self.charset))
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 6398: surrogates not allowed
librephotos-backend  | Bad Request: /api/user/
```
I could not set the admin's scan directory either.

**Comment by turnbeutelvergesser** [comment]
I could set a directory (Slightly confusing, why is it "data" and not the one I entered in .env?  That's the name inside docker, right?) and scan for photos after pointing to a small directory with only 10 images or so.  Might be that django trips over some non-english filenames or exif tags?  Need to dig deeper.

**Comment by turnbeutelvergesser** [comment]
Can confirm that there seems to be unicode stuff in my directory names that can't be encoded to bytes.  
```
File "/miniconda/lib/python3.8/site-packages/rest_framework/renderers.py", line 110, in render
librephotos-backend  |     return ret.encode()
librephotos-backend  | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 5896: surrogates not allowed
```
Now, if I change that to ```return ret.encode(errors='surrogateescape')``` I can see the directories and can choose which one to scan.  Problem is, there is only code from ```site-packages``` in the backtrace, where would be librephotos code to change that?

[...] got it.  The name that caused it was ```Route_de_Cr'$'\352''tes```

**Comment by derneuere** [comment]
So what are the steps to reproduce the error? Do I need a user with special characters or a folder with special characters?

You have to follow the request:
[2021-01-11 21:20:31 +0000] [158] [ERROR] Error handling request /api/dirtree/
This API is here: https://github.com/LibrePhotos/librephotos/blob/0668e3d39dfe61af5dfa1602c22ebe487b9c82c0/ownphotos/urls.py#L203
The view is here:
https://github.com/LibrePhotos/librephotos/blob/0668e3d39dfe61af5dfa1602c22ebe487b9c82c0/api/views.py#L1409-L1418
The function in question is probably here:
https://github.com/LibrePhotos/librephotos/blob/0668e3d39dfe61af5dfa1602c22ebe487b9c82c0/api/api_util.py#L42-L48

The other bad request is the following API:
Bad Request: /api/user/

**Comment by turnbeutelvergesser** [comment]
You need a directory name.  I just tried:
- Start with a fresh install and one normal directory as image directory (just to be on the safe side and not empty)
- Log in as admin and go to the "Admin Area", click edit icon before "not set" in scan directory of user admin
- You can select '/data' as directory and confirm
- mkdir <my_image_directory>/'20040606_Route_de_Cr'$'\352''tes'
- Got to "Admin Area", click the edit icon for scan directory of user admin
- Nothing appears under "Choose a directory from below", librophotos-backend log reports Django exception 
- rmdir 20040606_R*
- Now you can select the scan directory again.

**Comment by derneuere** [comment]
I tested it again and it seems to work now.
