### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#1333]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

I have migrated my librephotos setup to a new machine and I am now getting this error on startup in the backend service:

```
backend  | Traceback (most recent call last):
backend  |   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
backend  |     self.run()
backend  |   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
backend  |     self._target(*self._args, **self._kwargs)
backend  |   File "/usr/local/lib/python3.12/dist-packages/django_q/cluster.py", line 142, in __init__
backend  |     self.broker = broker or get_broker()
backend  |                             ^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django_q/brokers/__init__.py", line 193, in get_broker
backend  |     return orm.ORM(list_key=list_key)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django_q/brokers/__init__.py", line 13, in __init__
backend  |     self.connection = self.get_connection(list_key)
backend  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django_q/brokers/orm.py", line 20, in get_connection
backend  |     if transaction.get_autocommit(
backend  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/transaction.py", line 30, in get_autocommit
backend  |     return get_connection(using).get_autocommit()
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 464, in get_autocommit
backend  |     self.ensure_connection()
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/utils/asyncio.py", line 26, in inner
backend  |     return func(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 288, in ensure_connection
backend  |     with self.wrap_database_errors:
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/utils.py", line 91, in __exit__
backend  |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 289, in ensure_connection
backend  |     self.connect()
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/utils/asyncio.py", line 26, in inner
backend  |     return func(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/base/base.py", line 270, in connect
backend  |     self.connection = self.get_new_connection(conn_params)
backend  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/utils/asyncio.py", line 26, in inner
backend  |     return func(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
backend  |     connection = self.Database.connect(**conn_params)
backend  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/psycopg/connection.py", line 98, in connect
backend  |     attempts = conninfo_attempts(params)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
backend  |     raise e.OperationalError(str(last_exc))
backend  | django.db.utils.OperationalError: [Errno -3] Temporary failure in name resolution
```

it is not clear what it fails to connect to so i could troubleshoot it any futher

## Please provide additional information:
- 💻 Operating system: Ubuntu 20.4
- ⚙ Architecture (x86 or ARM):  x86
- 🔢 Librephotos version: reallibrephotos/librephotos:dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: reallibrephotos/librephotos:dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local file system

**Comment by derneuere** [comment]
It can't connect to Postgres. Do you have any steps for reproduction?

**Comment by savvasdalkitsis** [comment]
hm it might have been something to do with my new docker compose stack. I believe it is fixed now
