### ISSUE TITLE
Scan stops randomly (both nextcloud & local)

### ISSUE THREAD

**Issue by Stayer** [LibrePhotos/librephotos#137]
Hi! I have 795 photos on my nextcloud to process with librephotos. After run "scan photos" I have random hangs on this task. Here is logs: 

```
==> /app/logs/command_build_similarity_index.log <==

==> /app/logs/command_migrate.log <==

==> /app/logs/gunicorn_django.log <==

==> /app/logs/gunicorn_image_similarity.log <==

==> /app/logs/image_similarity.log <==

==> /app/logs/ownphotos.log <==
2021-01-15 09:03:30,369 : directory_watcher.py : scan_photos : 67 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/old/IMG-20200914-WA0002.jpeg
2021-01-15 09:03:30,369 : directory_watcher.py : scan_photos : 67 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/old/IMG-20201206-WA0000.jpeg
2021-01-15 09:03:30,369 : directory_watcher.py : scan_photos : 67 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/old/IMG-20201209-WA0001.jpeg
2021-01-15 09:03:30,369 : directory_watcher.py : scan_photos : 67 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/old/IMG-20201213-WA0000.jpeg
2021-01-15 09:03:30,369 : directory_watcher.py : scan_photos : 67 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/old/IMG-20201231-WA0001.jpeg
2021-01-15 09:03:30,369 : directory_watcher.py : scan_photos : 67 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/old/IMG-20210101-WA0000.jpeg
2021-01-15 09:03:30,791 : directory_watcher.py : scan_photos : 83 : INFO : begin handling of photo 1/600
2021-01-15 09:03:30,796 : directory_watcher.py : handle_new_image : 80 : INFO : job c2c8bed6-fbfd-4c65-aee0-f49b06793b0b: handling image /data/nextcloud_media/uploadCamera/IMG_20201107_143510.jpg
2021-01-15 09:03:32,883 : models.py : _generate_captions : 195 : INFO : generated places365 captions for image /code/protected_media/thumbnails_big/1282e285a95c8d9ab4640c09e98e9bdf1.jpg.
2021-01-15 09:03:32,969 : util.py : mapbox_reverse_geocode : 139 : INFO : mapbox returned status 200.

==> /app/logs/rqworker.log <==

==> /app/logs/show_migrate.log <==

==> /app/logs/gunicorn_django.log <==
[2021-01-15 09:03:39 +0000] [203] [INFO] Booting worker with pid: 203
```

Sometimes it proceeded for 5-10 photos, but typically it hangs after 1-2 photos. The same situation when I trying to copy photos from nextcloud to local and do the same job. 

Filesizes: 8-10 MB
System: Proxmox => Ubuntu VM => Docker
4 core, 8 GB RAM, ssd

Image: `reallibrephotos/librephotos            dev          f23ba1df6848   10 hours ago`

**Comment by derneuere** [comment]
Probably a rogue photo. After a scan is complete the photo is logged. So that means the next photo is causing the issue I think. The photos are sorted by path. Could you look into it?

**Comment by Stayer** [comment]
![image](https://user-images.githubusercontent.com/291735/104727037-ba9ad000-5745-11eb-81b4-6a15e7212b0c.png)

Yes, order is correct.
IMG_20201107_143735.jpg
IMG_20201107_143741.jpg
IMG_20201107_143750.jpg
IMG_20201107_143805.jpg

the next will be IMG_20201107_143750.jpg, but I think that it crashes on "IMG_20201107_143805.jpg", because there is no result for `"models.py : _add_to_album_date : 464 : INFO :"`. 

Sucessful order for images:

```
scan_photos
handle_new_image
_generate_captions
mapbox_reverse_geocode
_add_to_album_date
handle_new_image - elapsed time
```

failed image (IMG_20201107_143805.jpg)
```
scan_photos
handle_new_image
_generate_captions
mapbox_reverse_geocode
!stuck
```

for all of these images I have tags, and nextcloud see metadata.

after relaunch task, IMG_20201107_143810.jpg and next one was successful, then crashes again

**Comment by derneuere** [comment]
Well, maybe it has something to do with the exif data, but I am not sure yet...
Could you do a docker-compose down and then start it up with just docker-compose up. Maybe there is an unlogged exception.

**Comment by Stayer** [comment]
GET /settings

```
librephotos-backend  | Internal Server Error: /api/searchtermexamples/
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
librephotos-backend  |     response = self.process_exception_by_middleware(e, request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
librephotos-backend  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
librephotos-backend  |     return view_func(*args, **kwargs)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
librephotos-backend  |     return self.dispatch(request, *args, **kwargs)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
librephotos-backend  |     response = self.handle_exception(exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
librephotos-backend  |     self.raise_uncaught_exception(exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
librephotos-backend  |     raise exc
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
librephotos-backend  |     response = handler(request, *args, **kwargs)
librephotos-backend  |   File "/code/api/views.py", line 1423, in get
librephotos-backend  |     search_term_examples = get_search_term_examples(request.user)
librephotos-backend  |   File "/code/api/api_util.py", line 163, in get_search_term_examples
librephotos-backend  |     term_thing = random.choice(datum['things'])
librephotos-backend  |   File "/miniconda/lib/python3.8/random.py", line 290, in choice
librephotos-backend  |     raise IndexError('Cannot choose from an empty sequence') from None
librephotos-backend  | IndexError: Cannot choose from an empty sequence
```

GET /recent

```
librephotos-backend  | Internal Server Error: /api/searchtermexamples/
librephotos-backend  | Traceback (most recent call last):
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
librephotos-backend  |     response = get_response(request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
librephotos-backend  |     response = self.process_exception_by_middleware(e, request)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
librephotos-backend  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
librephotos-backend  |     return view_func(*args, **kwargs)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
librephotos-backend  |     return self.dispatch(request, *args, **kwargs)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
librephotos-backend  |     response = self.handle_exception(exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
librephotos-backend  |     self.raise_uncaught_exception(exc)
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
librephotos-backend  |     raise exc
librephotos-backend  |   File "/miniconda/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
librephotos-backend  |     response = handler(request, *args, **kwargs)
librephotos-backend  |   File "/code/api/views.py", line 1423, in get
librephotos-backend  |     search_term_examples = get_search_term_examples(request.user)
librephotos-backend  |   File "/code/api/api_util.py", line 163, in get_search_term_examples
librephotos-backend  |     term_thing = random.choice(datum['things'])
librephotos-backend  |   File "/miniconda/lib/python3.8/random.py", line 290, in choice
librephotos-backend  |     raise IndexError('Cannot choose from an empty sequence') from None
librephotos-backend  | IndexError: Cannot choose from an empty sequence
```

**Comment by derneuere** [comment]
That does not seem to have anything to do with scanning. Nevertheless, it is an exception.

I see that you only have one worker online. Is that correct? Maybe that is the missing piece.

**Comment by Stayer** [comment]
There are 5 workers:

librephotos-backend  | [2021-01-15 13:24:51 +0000] [115] [INFO] Starting gunicorn 20.0.4
librephotos-backend  | [2021-01-15 13:24:51 +0000] [115] [INFO] Listening at: http://0.0.0.0:8001 (115)
librephotos-backend  | [2021-01-15 13:24:51 +0000] [115] [INFO] Using worker: gevent
librephotos-backend  | [2021-01-15 13:24:51 +0000] [119] [INFO] Booting worker with pid: 119
librephotos-backend  | [2021-01-15 13:24:51 +0000] [120] [INFO] Booting worker with pid: 120
librephotos-backend  | [2021-01-15 13:24:51 +0000] [121] [INFO] Booting worker with pid: 121
librephotos-backend  | [2021-01-15 13:24:51 +0000] [122] [INFO] Booting worker with pid: 122
librephotos-backend  | [2021-01-15 13:24:51 +0000] [126] [INFO] Booting worker with pid: 126

**Comment by patschwork** [comment]
I got the same error. 
I copied sample images (*.CR3) into the folder. Yesterday the worker scanned 11 photos and stopped. After resetting the database, only 4 photos was scanned (same folder, same files). 

```sql
SELECT id, job_type, finished, failed, job_id, queued_at, started_at, finished_at, "result", started_by_id
FROM public.api_longrunningjob;
```
|id|job_type|finished|failed|job_id|queued_at|started_at|finished_at|result|started_by_id|
|--|--------|--------|------|------|---------|----------|-----------|------|-------------|
|7|1|true|true|bd4cf64e-68bd-4c32-b359-caf2a9465ab3|2022-06-04 09:15:19.048 +0200|2022-06-04 09:15:19.048 +0200|2022-06-04 09:15:24.674 +0200|{"progress": {"target": 154, "current": 0}, "new_photo_count": 0}|1|
|8|1|true|true|7aaf5b78-923f-4368-a0fd-5adad098fb88|2022-06-04 09:16:40.458 +0200|2022-06-04 09:16:40.458 +0200|2022-06-04 09:16:40.912 +0200|{"progress": {"target": 154, "current": 0}, "new_photo_count": 0}|1|

I also used the hint in the .env file to set
```sh
workerTimeOut=0
```
The files are in a local folder. 
Maybe related issues (#167 #94 ) are not helping....
