### ISSUE TITLE
Mistral gets 500 error

### ISSUE THREAD

**Issue by scepterus** [LibrePhotos/librephotos#1492]
# 🐛 Bug Report

* [X] 📁 I've Included a ZIP file containing my librephotos `log` files
* [_backend_logs.zip](https://github.com/user-attachments/files/17942613/_backend_logs.zip)
* [X] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
When choosing in the Admin panel the Large Language Model for processing, I get a 500 error.
Here's the output:
```
accept:
*/*
accept-encoding:
gzip, deflate
accept-language:
en-US,en;q=0.9,he;q=0.8,ar;q=0.7
authorization:
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzY3ODQxLCJpYXQiOjE3MzI3NjY5NDAsImp0aSI6ImYwNTVlMWQwOTBiYjRkZDdhMGU0ZDBiYzdlZjNmOTJmIiwidXNlcl9pZCI6MSwibmFtZSI6Im1pY2hhZWwiLCJpc19hZG1pbiI6dHJ1ZSwiZmlyc3RfbmFtZSI6Ik1pY2hhZWwiLCJsYXN0X25hbWUiOiJTaGFydml0Iiwic2Nhbl9kaXJlY3RvcnkiOiIvZGF0YSIsImNvbmZpZGVuY2UiOjAuNSwic2VtYW50aWNfc2VhcmNoX3RvcGsiOjAsIm5leHRjbG91ZF9zZXJ2ZXJfYWRkcmVzcyI6bnVsbCwibmV4dGNsb3VkX3VzZXJuYW1lIjpudWxsfQ.RX90vLqLx_K5lQtC8ap5fxlj_xJuTwd1jzIG0pnLIfM
connection:
keep-alive
content-length:
38
content-type:
application/json
cookie:
remember_standard_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IkU5bnJBc3BzRUl3Z2JsZFlyaVdCL0E9PSIsInZhbHVlIjoiUnRXR1NqWEhLc2Y4YmN2T0pRQ0U4Y3JIdi9sck00c25GZzEya0tUay9yNUptWDYwOXRlc0lXZExTN1FHQ0RnN3pOT3BScEpuQXhOSVd3d3FmOFNqSjJGbGpiYzRYT2Y3QW55N1BpNWlWbHRSblVVWXZuZGlSMjNwRTZrSTNoRVlWSVlOUUxQblN0bDBqdUFYdHJBS0hkYTVONjBVQ3M3ZEtwS2pYZjhKM2xoL29ic0dkUVRhYkRYdU0wNFJucmp2dkZ0YmxNaGNWNlhRditjd3pZZUtsTGFNZGRlNnlQNWJEK2Zqb21nNS9sVT0iLCJtYWMiOiJlNjkzYjQ5MjgyZjhmOTc2OGYzZWMwMDdlOTMxN2NiY2Y0MTE5ZGVhZjlmMmNkOWQzYWJiMThhMDQ4YTNhNmJmIiwidGFnIjoiIn0%3D; nd-player-41646d696e=98e7d6d2-78f4-46c3-8c9a-32ac4f8e1b0d; httpOnlyToken=89ffd6c4-a30b-4d42-b393-e140a8795b64; accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjhhM2RlNzUxLTM0MzQtNGJkZS1hZWM3LWZlMzE4OGI1N2U0MCJ9.eyJpYXQiOjE3MzIyMDYyMjAsImV4cCI6MTc2Mzc0MjIyMCwic3ViIjoiODI4MjIyNzY1NDgyOTAyNTMxIn0.XQbn3w5X9FavS_jOax6R3AqXvvfo50ZIJTTGrieGcTY; accessTokenVersion=1; refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMzM3MTc0MCwiaWF0IjoxNzMyNzY2OTQwLCJqdGkiOiJjNWRhNzRmNTM2NzU0MDI1OGFhZjQ1MWMzMTJjMzE4YiIsInVzZXJfaWQiOjEsIm5hbWUiOiJtaWNoYWVsIiwiaXNfYWRtaW4iOnRydWUsImZpcnN0X25hbWUiOiJNaWNoYWVsIiwibGFzdF9uYW1lIjoiU2hhcnZpdCIsInNjYW5fZGlyZWN0b3J5IjoiL2RhdGEiLCJjb25maWRlbmNlIjowLjUsInNlbWFudGljX3NlYXJjaF90b3BrIjowLCJuZXh0Y2xvdWRfc2VydmVyX2FkZHJlc3MiOm51bGwsIm5leHRjbG91ZF91c2VybmFtZSI6bnVsbH0.vI5rKxWr9eLcmmbjxgMKJGnFXs_8tF-otdt3vqReRQg; jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzY3ODQxLCJpYXQiOjE3MzI3NjY5NDAsImp0aSI6ImYwNTVlMWQwOTBiYjRkZDdhMGU0ZDBiYzdlZjNmOTJmIiwidXNlcl9pZCI6MSwibmFtZSI6Im1pY2hhZWwiLCJpc19hZG1pbiI6dHJ1ZSwiZmlyc3RfbmFtZSI6Ik1pY2hhZWwiLCJsYXN0X25hbWUiOiJTaGFydml0Iiwic2Nhbl9kaXJlY3RvcnkiOiIvZGF0YSIsImNvbmZpZGVuY2UiOjAuNSwic2VtYW50aWNfc2VhcmNoX3RvcGsiOjAsIm5leHRjbG91ZF9zZXJ2ZXJfYWRkcmVzcyI6bnVsbCwibmV4dGNsb3VkX3VzZXJuYW1lIjpudWxsfQ.RX90vLqLx_K5lQtC8ap5fxlj_xJuTwd1jzIG0pnLIfM; access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzY3ODQxLCJpYXQiOjE3MzI3NjY5NDAsImp0aSI6ImYwNTVlMWQwOTBiYjRkZDdhMGU0ZDBiYzdlZjNmOTJmIiwidXNlcl9pZCI6MSwibmFtZSI6Im1pY2hhZWwiLCJpc19hZG1pbiI6dHJ1ZSwiZmlyc3RfbmFtZSI6Ik1pY2hhZWwiLCJsYXN0X25hbWUiOiJTaGFydml0Iiwic2Nhbl9kaXJlY3RvcnkiOiIvZGF0YSIsImNvbmZpZGVuY2UiOjAuNSwic2VtYW50aWNfc2VhcmNoX3RvcGsiOjAsIm5leHRjbG91ZF9zZXJ2ZXJfYWRkcmVzcyI6bnVsbCwibmV4dGNsb3VkX3VzZXJuYW1lIjpudWxsfQ.RX90vLqLx_K5lQtC8ap5fxlj_xJuTwd1jzIG0pnLIfM
```

## 🔁 How can we reproduce it:
Select Mistral in that drop box.

## Please provide additional information:
💻 Operating system: TrueNAS Scale
⚙ Architecture (x86 or ARM): X86_64
🔢 Librephotos version: Latest-Gpu
📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
🐋 If Docker or Kubernets, provide docker-compose image tag: Latest
📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): ZFS
☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by Toparvion** [comment]
Here is the error I get in the same situation on LibrePhotos with backend version `ea8f612`:
> TypeError: Field 'id' expected a number but got <User: toparvion>.

<details><summary>Stacktrace</summary>
<p>

```
backend  | Internal Server Error: /api/sitesettings
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/fields/__init__.py", line 2053, in get_prep_value
backend  |     return int(value)
backend  |            ^^^^^^^^^^
backend  | TypeError: int() argument must be a string, a bytes-like object or a real number, not 'User'
backend  | 
backend  | The above exception was the direct cause of the following exception:
backend  | 
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/core/handlers/exception.py", line 55, in inner
backend  |     response = get_response(request)
backend  |                ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/core/handlers/base.py", line 197, in _get_response
backend  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
backend  |     return view_func(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/views/generic/base.py", line 104, in view
backend  |     return self.dispatch(request, *args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/rest_framework/views.py", line 509, in dispatch
backend  |     response = self.handle_exception(exc)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/rest_framework/views.py", line 469, in handle_exception
backend  |     self.raise_uncaught_exception(exc)
backend  |   File "/usr/local/lib/python3.12/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.12/dist-packages/rest_framework/views.py", line 506, in dispatch
backend  |     response = handler(request, *args, **kwargs)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/api/views/views.py", line 115, in post
backend  |     AsyncTask(download_models, User.objects.get(id=request.user)).run()
backend  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/manager.py", line 87, in manager_method
backend  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 623, in get
backend  |     clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
backend  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 1436, in filter
backend  |     return self._filter_or_exclude(False, args, kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
backend  |     clone._filter_or_exclude_inplace(negate, args, kwargs)
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
backend  |     self._query.add_q(Q(*args, **kwargs))
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/sql/query.py", line 1546, in add_q
backend  |     clause, _ = self._add_q(q_object, self.used_aliases)
backend  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/sql/query.py", line 1577, in _add_q
backend  |     child_clause, needed_inner = self.build_filter(
backend  |                                  ^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/sql/query.py", line 1492, in build_filter
backend  |     condition = self.build_lookup(lookups, col, value)
backend  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/sql/query.py", line 1319, in build_lookup
backend  |     lookup = lookup_class(lhs, rhs)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/lookups.py", line 27, in __init__
backend  |     self.rhs = self.get_prep_lookup()
backend  |                ^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
backend  |     return super().get_prep_lookup()
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
backend  |     return self.lhs.output_field.get_prep_value(self.rhs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.12/dist-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
backend  |     raise e.__class__(
backend  | TypeError: Field 'id' expected a number but got <User: toparvion>.
```
</p>
</details>

**Comment by derneuere** [comment]
Fixed on develop :)
