### ISSUE TITLE
name 'get_album_date' is not defined

### ISSUE THREAD

**Issue by alexislefebvre** [LibrePhotos/librephotos#163]
It looks like a function is missing, I see this in `ownphotos.log`:

```
2021-02-06 16:05:32,931 : directory_watcher.py : handle_new_image : 143 : ERROR : job 268763b8-f147-4de9-abc5-eca25b266822: could not load image /data/[…].jpg. reason: name 'get_album_date' is not defined
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 114, in handle_new_image
    photo._extract_date_time_from_exif()
  File "/code/api/models/photo.py", line 244, in _extract_date_time_from_exif
    old_album_date = self._find_album_date()
  File "/code/api/models/photo.py", line 223, in _find_album_date
    possible_old_album_date = get_album_date(date=None, owner=self.owner)
NameError: name 'get_album_date' is not defined
```

This method is called here: https://github.com/LibrePhotos/librephotos/blob/2128a6c05a83f59c86a7694fcff713cb2f9bbbb8/api/models/photo.py#L218-L223

But not defined in that file.

It's defined in another file: https://github.com/LibrePhotos/librephotos/blob/2128a6c05a83f59c86a7694fcff713cb2f9bbbb8/api/models/album_date.py#L61

**Comment by derneuere** [comment]
New image should be up in half an hour :)

**Comment by alexislefebvre** [comment]
Thanks! I'll test that.
