### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by guystreeter** [LibrePhotos/librephotos#213]
I pulled new images yesterday, removed my logs and database, and started a new scan. I found this in the back-end log:

```
Not Found: /api/jobs/
Unauthorized: /api/rqavailable/
Bad Request: /api/nextcloud/listdir/
Not Found: /api/jobs/
Downloading: "https://download.pytorch.org/models/resnet152-b121ed2d.pth" to /root/.cache/torch/hub/checkpoints/resnet152-b121ed2d.pth
 37%|███▋      | 85.0M/230M [00:15<00:26, 5.84MB/s]Not Found: /api/jobs/
100%|██████████| 230M/230M [00:41<00:00, 5.89MB/s] 
19:45:31 Cleaning registries for queue: default
19:59:01 Cleaning registries for queue: default
20:12:31 Cleaning registries for queue: default
20:26:01 Cleaning registries for queue: default
20:39:31 Cleaning registries for queue: default
20:53:01 Cleaning registries for queue: default
21:06:32 Cleaning registries for queue: default
21:20:02 Cleaning registries for queue: default
21:33:32 Cleaning registries for queue: default
21:47:02 Cleaning registries for queue: default
22:00:32 Cleaning registries for queue: default
22:14:02 Cleaning registries for queue: default
22:27:32 Cleaning registries for queue: default
22:41:02 Cleaning registries for queue: default
22:54:33 Cleaning registries for queue: default
23:08:03 Cleaning registries for queue: default
23:21:33 Cleaning registries for queue: default
23:35:03 Cleaning registries for queue: default
23:48:33 Cleaning registries for queue: default
00:02:03 Cleaning registries for queue: default
00:15:33 Cleaning registries for queue: default
00:29:03 Cleaning registries for queue: default
00:42:34 Cleaning registries for queue: default
00:56:04 Cleaning registries for queue: default
01:09:34 Cleaning registries for queue: default
01:23:04 Cleaning registries for queue: default
01:36:34 Cleaning registries for queue: default
01:50:04 Cleaning registries for queue: default
02:03:34 Cleaning registries for queue: default
02:17:04 Cleaning registries for queue: default
02:30:34 Cleaning registries for queue: default
02:44:05 Cleaning registries for queue: default
02:57:35 Cleaning registries for queue: default
03:11:05 Cleaning registries for queue: default
03:24:35 Cleaning registries for queue: default
03:38:05 Cleaning registries for queue: default
03:51:35 Cleaning registries for queue: default
04:05:05 Cleaning registries for queue: default
04:18:35 Cleaning registries for queue: default
04:32:05 Cleaning registries for queue: default
04:45:35 Cleaning registries for queue: default
04:59:06 Cleaning registries for queue: default
05:12:36 Cleaning registries for queue: default
05:26:06 Cleaning registries for queue: default
05:39:36 Cleaning registries for queue: default
05:53:06 Cleaning registries for queue: default
06:06:36 Cleaning registries for queue: default
06:20:06 Cleaning registries for queue: default
06:33:36 Cleaning registries for queue: default
06:47:06 Cleaning registries for queue: default
07:00:36 Cleaning registries for queue: default
07:14:06 Cleaning registries for queue: default
07:27:37 Cleaning registries for queue: default
07:41:07 Cleaning registries for queue: default
07:54:37 Cleaning registries for queue: default
08:08:07 Cleaning registries for queue: default
08:21:37 Cleaning registries for queue: default
08:35:07 Cleaning registries for queue: default
08:48:37 Cleaning registries for queue: default
09:02:07 Cleaning registries for queue: default
09:15:37 Cleaning registries for queue: default
09:29:07 Cleaning registries for queue: default
09:42:37 Cleaning registries for queue: default
09:56:08 Cleaning registries for queue: default
10:09:38 Cleaning registries for queue: default
10:23:08 Cleaning registries for queue: default
10:36:38 Cleaning registries for queue: default
10:50:08 Cleaning registries for queue: default
11:03:38 Cleaning registries for queue: default
11:17:08 Cleaning registries for queue: default
11:30:38 Cleaning registries for queue: default
11:44:08 Cleaning registries for queue: default
Unauthorized: /api/persons/
Unauthorized: /api/albums/place/list/
Unauthorized: /api/albums/user/list/
Unauthorized: /api/albums/thing/list/
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/albums/date/photohash/list/
Unauthorized: /api/stats/
Unauthorized: /api/user/1/
Internal Server Error: /api/searchtermexamples/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/api/views.py", line 1360, in get
    search_term_examples = get_search_term_examples(request.user)
  File "/code/api/api_util.py", line 163, in get_search_term_examples
    term_thing = random.choice(datum['things'])
  File "/usr/local/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
Not Found: /api/jobs/
11:57:38 Cleaning registries for queue: default
Unauthorized: /api/rqavailable/
Unauthorized: /api/rqavailable/
```

**Comment by guystreeter** [comment]
The backtrace is in the `gunicorn_django.log` file.

**Comment by derneuere** [comment]
Hey, thanks for the bug report. This is a duplicate of #175 I think. 

This is only related to the search at the top. It is the function which generates default examples to click on.

I will close this ticket due to being a duplicate :)
