### ISSUE TITLE
Can't Connect to Backend Server

### ISSUE THREAD

**Issue by bhusain966** [LibrePhotos/librephotos#221]
Greetings,

I've LibrePhotos installed on Synology (Docker) and it was working perfectly, however, after a restart (for an update) I am no longer able to longin :( I am getting this error

`No connection to backend server.`

Few lines of from the log:

```
2021/03/29 15:10:28 [error] 21#21: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /api/sitesettings/ HTTP/1.1", upstream: "http://192.168.160.2:8001/api/sitesettings/", host: "192.168.2.201:3333", referrer: "http://192.168.2.201:3333/login",

2021/03/29 15:12:09 [error] 21#21: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /api/sitesettings/ HTTP/1.1", upstream: "http://192.168.160.2:8001/api/sitesettings/", host: "192.168.2.201:3333", referrer: "http://192.168.2.201:3333/login",

2021/03/29 15:14:56 [error] 21#21: *56 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "POST /api/auth/token/obtain/ HTTP/1.1", upstream: "http://192.168.160.2:8001/api/auth/token/obtain/", host: "192.168.2.201:3333", referrer: "http://192.168.2.201:3333/login",

192.168.160.1 - - [29/Mar/2021:15:14:56 +0000] "POST /api/auth/token/obtain/ HTTP/1.1" 502 559 "http://192.168.2.201:3333/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36"
```

Although all containers are working just fine and healthy. How can I fix this? any ideas?

**Comment by ThirumlaDevi** [comment]
Hi @bhusain966. I was looking into the [docker-compose.yml](https://raw.githubusercontent.com/LibrePhotos/librephotos-docker/main/docker-compose.yml) file. Though docker-compose defines it's own default network,  you can try declaring all of the containers under the same network. You can also make use of your default network throughout the containers. Could you use [this](https://docs.docker.com/compose/networking/) reference to do the same? 
This solved similar issues that I faced previously 😄

**Comment by bhusain966** [comment]
Thanks! @ThirumlaDevi for the tip.
so I have added  `network_mode: host` at each service in the yaml file and rebuilt the containers.  

When I navigate to (http://host:3000), I get the login screen and when I enter my credentials I get the same (Can't Connect to backend) error.  Also, it seems I am getting some other errors in the following containers:


 **liraphotos_proxy_1:**

```
2021/03/29 17:57:17 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19,
2021-03-29T17:55:15.238409732Z 2021/03/29 17:55:15 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19,
2021-03-29T17:55:15.238527581Z nginx: [emerg] host not found in upstream "frontend" in /etc/nginx/nginx.conf:19,
2021-03-29T17:56:16.049107087Z /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration,
2021-03-29T17:56:16.049537468Z /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/,
2021-03-29T17:56:16.050060103Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh,
2021-03-29T17:56:16.052216362Z 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled,
2021-03-29T17:56:16.052322883Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh,
2021-03-29T17:55:15.231580397Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh,
2021-03-29T17:55:15.233773620Z /docker-entrypoint.sh: Configuration complete; ready for start up
```
**librephotos_backend_1:**
```
2021-03-29T18:00:48.290277747Z     conn = _connect(dsn, connection_factory=connection_factory, **kwasync),
2021-03-29T18:00:48.290331688Z django.db.utils.OperationalError: could not translate host name "db" to address: No address associated with hostname,
2021-03-29T18:00:48.290373433Z ,
2021-03-29T18:00:54.705608228Z Traceback (most recent call last):,
2021-03-29T18:00:54.705897467Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection,
2021-03-29T18:00:54.705949365Z     self.connect(),
2021-03-29T18:00:54.705972538Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
2021-03-29T18:00:54.705995587Z     return func(*args, **kwargs),
2021-03-29T18:00:54.706013124Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect,
2021-03-29T18:00:54.706038717Z     self.connection = self.get_new_connection(conn_params),
2021-03-29T18:00:54.706056501Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
2021-03-29T18:00:54.706074636Z     return func(*args, **kwargs),
2021-03-29T18:00:54.706089466Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection,
2021-03-29T18:00:54.706147904Z     connection = Database.connect(**conn_params),
2021-03-29T18:00:54.706167692Z   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect,
2021-03-29T18:00:54.706193065Z     conn = _connect(dsn, connection_factory=connection_factory, **kwasync),
2021-03-29T18:00:54.706212794Z psycopg2.OperationalError: could not translate host name "db" to address: No address associated with hostname,
2021-03-29T18:00:54.706237650Z ,
2021-03-29T18:00:54.706253803Z ,
2021-03-29T18:00:54.706268841Z The above exception was the direct cause of the following exception:,
2021-03-29T18:00:54.706310331Z ,
2021-03-29T18:00:54.706324844Z Traceback (most recent call last):,
2021-03-29T18:00:54.706340313Z   File "manage.py", line 22, in <module>,
2021-03-29T18:00:54.706364238Z     execute_from_command_line(sys.argv),
2021-03-29T18:00:54.706381378Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line,
2021-03-29T18:00:54.706404259Z     utility.execute(),
2021-03-29T18:00:54.706423476Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute,
2021-03-29T18:00:54.706487194Z     self.fetch_command(subcommand).run_from_argv(self.argv),
2021-03-29T18:00:54.706536771Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv,
2021-03-29T18:00:54.706612712Z     self.execute(*args, **cmd_options),
2021-03-29T18:00:54.706650165Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 368, in execute,
2021-03-29T18:00:54.706739075Z     self.check(),
2021-03-29T18:00:54.706768109Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check,
2021-03-29T18:00:54.706870201Z     all_issues = checks.run_checks(,
2021-03-29T18:00:54.706893396Z   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks,
2021-03-29T18:00:54.706930224Z     new_errors = check(app_configs=app_configs, databases=databases),
2021-03-29T18:00:54.706959157Z   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config,
2021-03-29T18:00:54.706985039Z     return check_resolver(resolver),
2021-03-29T18:00:54.707001185Z   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver,
2021-03-29T18:00:54.707034544Z     return check_method(),
2021-03-29T18:00:54.707057664Z   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check,
2021-03-29T18:00:54.707181781Z     for pattern in self.url_patterns:,
2021-03-29T18:00:54.707209677Z   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__,
2021-03-29T18:00:54.707234070Z     res = instance.__dict__[self.name] = self.func(instance),
2021-03-29T18:00:54.707253136Z   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns,
2021-03-29T18:00:54.707438029Z     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module),
2021-03-29T18:00:54.707465749Z   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__,
2021-03-29T18:00:54.707496007Z     res = instance.__dict__[self.name] = self.func(instance),
2021-03-29T18:00:54.707527976Z   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module,
2021-03-29T18:00:54.707674224Z     return import_module(self.urlconf_name),
2021-03-29T18:00:54.707698194Z   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module,
2021-03-29T18:00:54.707745389Z     return _bootstrap._gcd_import(name[level:], package, level),
2021-03-29T18:00:54.707771881Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
2021-03-29T18:00:54.707805286Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
2021-03-29T18:00:54.707848481Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked,
2021-03-29T18:00:54.707890010Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked,
2021-03-29T18:00:54.707931481Z   File "<frozen importlib._bootstrap_external>", line 783, in exec_module,
2021-03-29T18:00:54.707976267Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
2021-03-29T18:00:54.708017141Z   File "/code/ownphotos/urls.py", line 16, in <module>,
2021-03-29T18:00:54.708071878Z     from api import views,
2021-03-29T18:00:54.708095836Z   File "/code/api/views.py", line 490, in <module>,
2021-03-29T18:00:54.708229302Z     class FaceViewSet(viewsets.ModelViewSet):,
2021-03-29T18:00:54.708253794Z   File "/usr/local/lib/python3.8/site-packages/six.py", line 878, in wrapper,
2021-03-29T18:00:54.708481400Z     return metaclass(cls.__name__, cls.__bases__, orig_vars),
2021-03-29T18:00:54.708507869Z   File "/code/api/drf_optimize.py", line 102, in __new__,
2021-03-29T18:00:54.708549918Z     if queryset:,
2021-03-29T18:00:54.708574772Z   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 291, in __bool__,
2021-03-29T18:00:54.708668507Z     self._fetch_all(),
2021-03-29T18:00:54.708690551Z   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all,
2021-03-29T18:00:54.709038893Z     self._result_cache = list(self._iterable_class(self)),
2021-03-29T18:00:54.709084558Z   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__,
2021-03-29T18:00:54.709114882Z     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size),
2021-03-29T18:00:54.709135688Z   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql,
2021-03-29T18:00:54.709392434Z     cursor = self.connection.cursor(),
2021-03-29T18:00:54.709420055Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
2021-03-29T18:00:54.709442371Z     return func(*args, **kwargs),
2021-03-29T18:00:54.709458256Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor,
2021-03-29T18:00:54.709550030Z     return self._cursor(),
2021-03-29T18:00:54.709577296Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor,
2021-03-29T18:00:54.709650538Z     self.ensure_connection(),
2021-03-29T18:00:54.709671983Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
2021-03-29T18:00:54.709698243Z     return func(*args, **kwargs),
2021-03-29T18:00:54.709720097Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection,
2021-03-29T18:00:54.709794491Z     self.connect(),
2021-03-29T18:00:54.709816346Z   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__,
2021-03-29T18:00:54.709856457Z     raise dj_exc_value.with_traceback(traceback) from exc_value,
2021-03-29T18:00:54.709881288Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection,
2021-03-29T18:00:54.709954855Z     self.connect(),
2021-03-29T18:00:54.709976304Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
2021-03-29T18:00:54.709996812Z     return func(*args, **kwargs),
2021-03-29T18:00:54.710011724Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect,
2021-03-29T18:00:54.710083884Z     self.connection = self.get_new_connection(conn_params),
2021-03-29T18:00:54.710106475Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
2021-03-29T18:00:54.710134719Z     return func(*args, **kwargs),
2021-03-29T18:00:54.710156806Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection,
2021-03-29T18:00:54.710220511Z     connection = Database.connect(**conn_params),
2021-03-29T18:00:54.710242420Z   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect,
2021-03-29T18:00:54.710308935Z     conn = _connect(dsn, connection_factory=connection_factory, **kwasync),
2021-03-29T18:00:54.710332327Z django.db.utils.OperationalError: could not translate host name "db" to address: No address associated with hostname,
2021-03-29T18:00:54.710355306Z ,

```

**librephotos_frontend_1:**  This sounds to be just an update notification.

```
installing frontend,
,
up to date, audited 1642 packages in 24s,
,
44 vulnerabilities (34 low, 5 moderate, 5 high),
,
To address issues that do not require attention, run:,
  npm audit fix,
,
To address all issues possible (including breaking changes), run:,
  npm audit fix --force,
,
Some issues need review, and may require choosing,
a different dependency.,
,
Run `npm audit` for details.,
npm notice ,
npm notice New minor version of npm available! 7.0.15 -> 7.7.5,
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.7.5>,
npm notice Run `npm install -g npm@7.7.5` to update!,
npm notice ,
serving frontend,
productions running frontend,
INFO: Accepting connections at http://localhost:3000,
```
What am I doing wrong? 

Thanks!

**Comment by derneuere** [comment]
It looks like the backend can't connect to your database.  It can't find the service called "db"

**Comment by bhusain966** [comment]
Thanks. I have figured it out from the logs however I can't figure out "why" I didn't do anything except restarting the synology🤔

I've tried to rebuild the services by running docker-compose again but same thing, keep getting can't connect the backend server.

**Comment by darrepac** [comment]
Did you wait a bit? On my side I have always such error then about 20min later I can connect without problem....

**Comment by ThirumlaDevi** [comment]
@bhusain966 @darrepac Apologies for the late reply. The issue is in the docker-compose file. The port declarations were incorrect. I fixed this issue and I am able to now login to the application, but since this project gets the docker-compose file from a host location, I am unable to raise a PR with this fix. Could you please let me know, if I am incorrect with this assumption? Could you please let me know if you want me to share the updated docker-compose file here?
![image](https://user-images.githubusercontent.com/67866345/113502505-4a346b80-954a-11eb-9032-e68fcf49c597.png)

**Comment by ThirumlaDevi** [comment]
@bhusain966 I read the docker network docs [reference](https://docs.docker.com/compose/networking/) and i couldn't find the details on parameter named as "network_mode". Could you please provide some reference for better understanding on this newly set parameter?

**Comment by bhusain966** [comment]
Thanks @ThirumlaDevi for your input.  Actually, I've deleted all containers (not the data folders) and re-built from the same docker-compose.yml file and everything seems to be working fine now.
i still don't know what was the issue nor what solved it after rebuilding as I am using the exact same docker-compose file.

In some docker documentation (network_mode: host ) forces the containers to use the host network instead of creating a default network by the folder_name.  I tried and didn't work, so I removed it.

Thanks for your help!

**Comment by darrepac** [comment]
The docker image has changes several times those last days, it could be the reason why now it works

**Comment by ThirumlaDevi** [comment]
@bhusain966 I'm happy that you are unblocked, but i'll just let you know what error I fixed and how this issue got resolved in my end. Probably try removing all of the images involved in this project including the dbs and then try this. 
When I pulled and up-ed the docker containers using `docker-compose up` command, could derive that the frontend and backend weren;t connecting because the backend wasn't properly connecting with the db ( there was a connection error)
```
statd: unrecognized service
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.3) and accepting
	TCP/IP connections on port 5432?
```

I was able to infer from the docker container logs and `docker ps` command that the postgres db container port and exposed port wasn't specified properly, instead it was just specified that there was tcp connection in port 5432. Then I removed the image using docker rmi and added the port configuration "5432:5432" in the docker-compose file.
I upped the setup using `docker-compose up`, the frontend was able to successfully connect with backend. I was also able to login successfully as I have indicated in the screenshot. 
I request you to just look into this with a fresh docker setup. Thanks.

**Comment by bhusain966** [comment]
Well, that was some short happy moment!  Today it's back to the same error, Can't connect to the backend server. 
I think I have (watchtower) container running which updates the containers automatically, and after each update, I am facing this issue.
I will try to declare the port in the docker-compose file and rebuild and I hope this issue is solved once and for all.

Will keep you all posted.

**Comment by bhusain966** [comment]
> I was able to infer from the docker container logs and `docker ps` command that the postgres db container port and exposed port wasn't specified properly, instead it was just specified that there was tcp connection in port 5432. Then I removed the image using docker rmi and added the port configuration "5432:5432" in the docker-compose file.
 
Just wanted to make sure, port configuration under which service?  db or backend?  I have tried to do as above however, in synolgy I always get port already utilized issue 

```
sudo netstat -anp | grep 5432
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      21606/postgres      
udp6       0      0 fe80::5432:70ff:fe2:123 :::*                                9797/ntpd           
unix  2      [ ACC ]     STREAM     LISTENING     403864321 21606/postgres       /run/postgresql/.s.PGSQL.5432
unix  2      [ ]         DGRAM                    402904077 5432/-sh             

```

whenever I kill this service it gets restarted automatically.
I have tried to change the container port "5433:5432" and I got the same error (can't connect to backend server).

still trying to figure this out..

**Comment by bhusain966** [comment]
> @bhusain966 @darrepac Apologies for the late reply. The issue is in the docker-compose file. The port declarations were incorrect. I fixed this issue and I am able to now login to the application, but since this project gets the docker-compose file from a host location, I am unable to raise a PR with this fix. Could you please let me know, if I am incorrect with this assumption? Could you please let me know if you want me to share the updated docker-compose file here?

Yes please! share the updated docker-compose file.  Much appreciated!

**Comment by ThirumlaDevi** [comment]
@bhusain966 I can see that you have specified that you rebuild the docker-compose file, but you will notice that in your case image rebuild process gets skipped. This is because you don't have any Dockerfile or any changes to that Dockerfile which ultimately builds the image layer. Hence, you need to remove the image using `docker rmi <image id>` command and re-run the `docker-compose up` command which will automatically pull and up the image with proper container configurations. 

Also I noticed that you have now configured a specific image version for redis and postgres in your hosted [docker-compose file](https://raw.githubusercontent.com/LibrePhotos/librephotos-docker/main/docker-compose.yml). However, the below change was done in your prev configured docker-compose.yml file which had no such versions configured.
_**Note:  Please remove all of the postgres images using `docker rmi` command before running the below change.**_ 

```
# DO NOT EDIT
# The .env file has everything you need to edit.
# Run options:
# 1. Use prebuilt images (preferred method):
#   run cmd: docker-compose up -d
# 2. Build images on your own machine:
#   build cmd: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
#   run cmd: docker-compose up -d

version: '3.8'
services:
  proxy:
    image: reallibrephotos/librephotos-proxy:${tag}
    restart: always
    volumes:
      - ${myPhotos}:/data
      - ${proMedia}:/protected_media
    ports:
      - ${httpPort}:80
    depends_on:
      - backend
      - frontend

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${dbUser}
      - POSTGRES_PASSWORD=${dbPass}
      - POSTGRES_DB=${dbName}
    ports:
      - "5432:5432"
    volumes:
      - ${dbLocation}:/var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0

  frontend:
    image: reallibrephotos/librephotos-frontend:${tag}
    restart: always
    depends_on:
      - backend

  backend:
    image: reallibrephotos/librephotos:${tag}
    restart: always
    volumes:
      - ${myPhotos}:/data
      - ${proMedia}:/protected_media
      - ${logLocation}:/logs
      - ${cachedir}:/root/.cache

    environment:
      - SECRET_KEY=${shhhhKey}
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${mapApiKey}
      - TIME_ZONE=${timeZone}
      - WEB_CONCURRENCY=${gunniWorkers}
      - SKIP_PATTERNS=${skipPatterns}
      - DEBUG=0

    # Wait for Postgres
    depends_on:
      - db

  redis:
    image: redis
    restart: always

```
Please do let me know if everything is fine🙂.

**Comment by bhusain966** [comment]
Perfect! 

I'll you know how it goes!

Much appreciated.

**Comment by darrepac** [comment]
I am using docker-compose install, and never got such error / port problem...

**Comment by derneuere** [comment]
@bhusain966 Did it work?

**Comment by bhusain966** [comment]
hey @derneuere !

Actually yes, I waited for some time till I get the problem again "Can't connect to backend server" and when it happened, I have deleted all images and volumes and used the YAML file you have shared, and rebuilt the containers.  So far so good, I haven't got this error yet!  

I've noticed one thing, an old worker job is still showing as running, although it's been almost a month since it started.  Is there a way to kill this job? (see attached)

Many thanks!
<img width="1787" alt="Screen Shot 2021-04-27 at 3 14 34 PM" src="https://user-images.githubusercontent.com/81579319/116239558-77e88b00-a76b-11eb-933e-1955ff7dce05.png">

**Comment by derneuere** [comment]
@bhusain966 The worker is probably not running anymore. We don't handle jobs that were killed at all, so they show up in the entries as running. You can just delete the log entry.

**Comment by bhusain966** [comment]
Thanks.   I did remove it, however, on the top right corner the worker status shows as "Busy"  would this affect anything, performance,
<img width="308" alt="Screen Shot 2021-04-27 at 3 42 02 PM" src="https://user-images.githubusercontent.com/81579319/116243049-34901b80-a76f-11eb-9cd6-c533fda91bc3.png">
 or otherwise
