### ISSUE TITLE
Nextcloud scan broken

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#32]
I installed newest images from docker, on fresh server and nextcloud scan is not working. 

Logs:
```
2020-12-12 17:01:05,131 : directory_watcher.py : isValidMedia : 20 : ERROR : Following image throwed an exception: /Folder/Second_Folder/
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 17, in isValidMedia
    filetype = magic.from_file(p, mime=True)
  File "/miniconda/lib/python3.8/site-packages/magic.py", line 153, in from_file
    return m.from_file(filename)
  File "/miniconda/lib/python3.8/site-packages/magic.py", line 95, in from_file
    with open(filename):
FileNotFoundError: [Errno 2] No such file or directory: '/Folder/Second_Folder/'

2020-12-12 17:01:33,176 : directory_watcher.py : isValidMedia : 20 : ERROR : Following image throwed an exception: /Folder/Second_Folder/18-09-21 07-51-50 0959.jpg
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 17, in isValidMedia
    filetype = magic.from_file(p, mime=True)
  File "/miniconda/lib/python3.8/site-packages/magic.py", line 153, in from_file
    return m.from_file(filename)
  File "/miniconda/lib/python3.8/site-packages/magic.py", line 95, in from_file
    with open(filename):
FileNotFoundError: [Errno 2] No such file or directory: '/Folder/Second_Folder/18-09-21 07-51-50 0959.jpg'
```

Local scan is working

**Comment by derneuere** [comment]
I created a new image. Please do a docker-compose pull and then a docker-compose up. It should work now. If it does close the issue :)

**Comment by sysoppl** [comment]
Well, pulled new image, started container and same as before, instant "job finished"
```
2020-12-13 10:43:40,465 : image_similarity.py : build_image_similarity_index : 28 : INFO : builing similarity index for user USER1
2020-12-13 10:43:40,472 : image_similarity.py : build_image_similarity_index : 28 : INFO : builing similarity index for user USER2
2020-12-13 10:43:40,476 : image_similarity.py : build_image_similarity_index : 28 : INFO : builing similarity index for user USER3
2020-12-13 10:43:40,480 : image_similarity.py : build_image_similarity_index : 28 : INFO : builing similarity index for user USER4
2020-12-13 10:45:12,512 : directory_watcher.py : scan_photos : 59 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/FOLDER/FOLDER2/FOLDER3/
2020-12-13 10:45:12,512 : directory_watcher.py : scan_photos : 59 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/FOLDER/FOLDER2/FOLDER4/
2020-12-13 10:45:12,512 : directory_watcher.py : scan_photos : 59 : INFO : Downloaded photo from nextcloud to /data/nextcloud_media/FOLDER/FOLDER2/FOLDER5/
2020-12-13 10:45:12,520 : directory_watcher.py : scan_photos : 75 : INFO : begin handling of photo 1/3
2020-12-13 10:45:12,520 : directory_watcher.py : scan_photos : 97 : ERROR : [Errno 21] Is a directory: '/data/nextcloud_media/FOLDER/FOLDER2/FOLDER3/'
Traceback (most recent call last):
  File "/code/nextcloud/directory_watcher.py", line 76, in scan_photos
    handle_new_image(user, image_path, job_id)
  File "/code/api/directory_watcher.py", line 31, in handle_new_image
    if isValidMedia(open(image_path,"rb").read(2048)):
IsADirectoryError: [Errno 21] Is a directory: '/data/nextcloud_media/FOLDER/FOLDER2/FOLDER3/'
2020-12-13 10:45:13,696 : views.py : list : 840 : INFO : querying & serializing took 0.01 seconds
2020-12-13 10:45:20,557 : views.py : list : 840 : INFO : querying & serializing took 0.01 seconds
```

This time log does not contain several thousands of error messages, but only this one above

**Comment by derneuere** [comment]
Alright. I created a new image. Please do a docker-compose pull and then a docker-compose up. It should work now. If it does close the issue :)
