### ISSUE TITLE
cant start scan from cli

### ISSUE THREAD

**Issue by phynias** [LibrePhotos/librephotos#323]
## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### How is you picture library mounted on the host (or in the virtual machine):
Local file system

> ### Description of issue:
> error when trying to start scan from the cli for docker.
> 
> # docker exec --user root backend python3 manage.py scan
> Traceback (most recent call last):
>   File "/code/manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/code/api/management/commands/scan.py", line 12, in handle
>     scan_photos(user,uuid.uuid4())
> TypeError: scan_photos() missing 1 required positional argument: 'job_id'
> 

### How can we reproduce it:

docker exec --user root backend python3 manage.py scan

#### Additional Information:

* Include a ZIP file containing your `log` files.

**Comment by phynias** [comment]
[my-logs.zip](https://github.com/LibrePhotos/librephotos/files/7027244/my-logs.zip)
