### ISSUE TITLE
Viewing autocreated albums doesnt work. 

### ISSUE THREAD

**Issue by nowheretobefound** [LibrePhotos/librephotos#337]
"Showing 0 autocreated albums" even though there are more than 900 events created. Get this stacktrace

`==> gunicorn_django.log <==
Internal Server Error: /api/albums/auto/list/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/options.py", line 575, in get_field
    return self.fields_map[field_name]
KeyError: 'rating'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/cache/decorators.py", line 54, in inner
    return this.process_cache_response(
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/cache/decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/cache/decorators.py", line 116, in calculate_key
    return key_func(
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/key_constructor/constructors.py", line 29, in __call__
    return self.get_key(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/key_constructor/constructors.py", line 44, in get_key
    value = self._get_key(
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/key_constructor/constructors.py", line 73, in _get_key
    self.get_data_from_bits(**_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/key_constructor/constructors.py", line 89, in get_data_from_bits
    result_dict[bit_name] = bit_instance.get_data(
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/key_constructor/bits.py", line 227, in get_data
    return self._get_queryset_query_string(queryset)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_extensions/key_constructor/bits.py", line 202, in _get_queryset_query_string
    return force_str(queryset.query.__str__())
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/query.py", line 256, in __str__
    sql, params = self.sql_with_params()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/query.py", line 264, in sql_with_params
    return self.get_compiler(DEFAULT_DB_ALIAS).as_sql()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 498, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 55, in pre_sql_setup
    self.setup_query()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 46, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 227, in get_select
    cols = self.get_default_columns()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 655, in get_default_columns
    only_load = self.deferred_to_columns()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1080, in deferred_to_columns
    self.query.deferred_to_data(columns, self.query.get_loaded_field_names_cb)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/query.py", line 686, in deferred_to_data
    field = opts.get_field(parts[-1])
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/options.py", line 577, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: AlbumAuto has no field named 'rating'
Unauthorized: /api/rqavailable/
`

**Comment by derneuere** [comment]
This works now again

**Comment by EvilDrW** [comment]
i have the same issue... can you explain what you did so that it works again?
