### ISSUE TITLE
Scan Face fails with Python traceback

### ISSUE THREAD

**Issue by guystreeter** [LibrePhotos/librephotos#366]
## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (ext4)

### Description of issue:
"Scan Faces" fails with a Python traceback

### How can we reproduce it:
Run "Scan faces"

#### Additional Information:

```
2021-09-26 16:39:31,923 : directory_watcher.py : scan_faces : 363 : ERROR : An error occured: 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/code/api/directory_watcher.py", line 324, in face_scanner
    photo._extract_faces()
  File "/code/api/models/photo.py", line 507, in _extract_faces
    face_encodings = face_recognition.face_encodings(
  File "/usr/local/lib/python3.9/dist-packages/face_recognition/api.py", line 210, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
  File "/usr/local/lib/python3.9/dist-packages/face_recognition/api.py", line 210, in <listcomp>
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
TypeError: compute_face_descriptor(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),uint8], face: _dlib_pybind11.full_object_detection, num_jitters: int=0, padding: float=0.25) -> _dlib_pybind11.vector
    2. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),uint8], num_jitters: int=0) -> _dlib_pybind11.vector
    3. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),uint8], faces: _dlib_pybind11.full_object_detections, num_jitters: int=0, padding: float=0.25) -> _dlib_pybind11.vectors
    4. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),uint8]], batch_faces: List[_dlib_pybind11.full_object_detections], num_jitters: int=0, padding: float=0.25) -> _dlib_pybind11.vectorss
    5. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),uint8]], num_jitters: int=0) -> _dlib_pybind11.vectors

Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x7f997dca8130>, array([[254, 254, 254, ...,  15,   0,   9],
       [254, 254, 254, ...,   6,   0,   2],
       [254, 254, 254, ...,   3,   4,   6],
       ...,
       [255, 255, 255, ...,  68,  52,  46],
       [255, 255, 255, ...,  95,  60,  51],
       [255, 255, 255, ..., 125,  54,  50]], dtype=uint8), <_dlib_pybind11.full_object_detection object at 0x7f99b7a65270>, 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 360, in scan_faces
    pool.starmap(face_scanner, all)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: compute_face_descriptor(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),uint8], face: _dlib_pybind11.full_object_detection, num_jitters: int=0, padding: float=0.25) -> _dlib_pybind11.vector
    2. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),uint8], num_jitters: int=0) -> _dlib_pybind11.vector
    3. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),uint8], faces: _dlib_pybind11.full_object_detections, num_jitters: int=0, padding: float=0.25) -> _dlib_pybind11.vectors
    4. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),uint8]], batch_faces: List[_dlib_pybind11.full_object_detections], num_jitters: int=0, padding: float=0.25) -> _dlib_pybind11.vectorss
    5. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),uint8]], num_jitters: int=0) -> _dlib_pybind11.vectors

Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x7f997dca8130>, array([[254, 254, 254, ...,  15,   0,   9],
       [254, 254, 254, ...,   6,   0,   2],
       [254, 254, 254, ...,   3,   4,   6],
       ...,
       [255, 255, 255, ...,  68,  52,  46],
       [255, 255, 255, ...,  95,  60,  51],
       [255, 255, 255, ..., 125,  54,  50]], dtype=uint8), <_dlib_pybind11.full_object_detection object at 0x7f99b7a65270>, 1
2021-09-26 16:39:31,931 : directory_watcher.py : scan_faces : 367 : INFO : Added 537 faces
2021-09-27 08:43:18,520 : views.py : list : 612 : INFO : querying & serializing took 32.43 seconds
```
[logs.zip](https://github.com/LibrePhotos/librephotos/files/7236884/logs.zip)

**Comment by guystreeter** [comment]
Turns out scan faces was failing due to file permission problems. It would be nice to see that in the UI, instead of having to scan through log files.
