### ISSUE TITLE
"TypeError: decode() got an unexpected keyword argument 'verify'"

### ISSUE THREAD

**Issue by zaccrites** [LibrePhotos/librephotos#373]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [X] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Debian 11

### What architecture is LibrePhotos running on:
x64 or ARM

x64

### How is LibrePhotos installed:
Docker, Kubernetes, or .deb

Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker version 20.10.9, build c2ea9bc

docker-compose version 1.29.2, build 5becea4c

```
$ docker image ls
REPOSITORY                             TAG       IMAGE ID       CREATED       SIZE
reallibrephotos/librephotos            dev       8f8bc6dd6f49   8 hours ago   7.82GB
redis                                  6         b8477f2e393b   2 days ago    113MB
reallibrephotos/librephotos-frontend   dev       676e7c73dbe2   8 days ago    873MB
postgres                               13        cd4b5373985e   9 days ago    371MB
hello-world                            latest    feb5d9fea6a5   2 weeks ago   13.3kB
reallibrephotos/librephotos-proxy      dev       253354a2fa11   5 weeks ago   133MB
```

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB

Local file system (ZFS)

### Description of issue:

After logging in as admin, the page never loads. Examining the JavaScript console shows 500 errors on the route `/api/rqavailable`. The docker logs give this:

```
Internal Server Error: /api/rqavailable/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/authentication.py", line 35, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/authentication.py", line 89, in get_validated_token
    return AuthToken(raw_token)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/tokens.py", line 42, in __init__
    self.payload = token_backend.decode(token, verify=verify)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/backends.py", line 68, in decode
    return jwt.decode(token, self.verifying_key, algorithms=[self.algorithm], verify=verify,
TypeError: decode() got an unexpected keyword argument 'verify'
```

Which led me to this SO question:
https://stackoverflow.com/questions/69485121/django-rest-framework-simple-jwt-decode-got-an-unexpected-keyword-argument-v

And to this commit on PyJWT which removes the `**kwargs` from the argument list of `decode`, resulting in this problem.
https://github.com/jpadilla/pyjwt/commit/5fe7f2b28ffcd27a3e520be750858944889112ef#diff-6893ad4a1c5a36b8af3028db8c8bc3b62418149843fc382faf901eaab008e380

### How can we reproduce it:
Install via docker-compose following the instructions

![image](https://user-images.githubusercontent.com/5161225/136709798-8c0ab56d-1e63-4db4-95db-903b461e7696.png)

**Comment by zaccrites** [comment]
Workaround: downgrade to PyJWT 2.1.0

```
$ docker exec -it <backend-container-id> bash
# pip install -U PyJWT==2.1.0
# exit
$ docker restart <backend-container-id>
```
