### ISSUE TITLE
Scan hangs after a few videos

### ISSUE THREAD

**Issue by kyangk** [LibrePhotos/librephotos#406]
### What Operating system and version is LibrePhotos running on:
```
$ uname -a
Linux piserver 5.4.0-1043-raspi #47-Ubuntu SMP PREEMPT Mon Aug 23 09:41:31 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### What architecture is LibrePhotos running on:
arm64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
docker-compose.yml 

```
version: "3.3"
services:
  proxy:
    image: reallibrephotos/librephotos-proxy:${tag}
    restart: always
    volumes:
      - ${myPhotos}:/data
      - ${proMedia}:/protected_media
    ports:
      - ${httpPort}:80
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${dbUser}
      - POSTGRES_PASSWORD=${dbPass}
      - POSTGRES_DB=${dbName}
    volumes:
      - ${dbLocation}:/var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0

  frontend:
    image: reallibrephotos/librephotos-frontend:${tag}
    restart: always
    depends_on:
      - backend

  backend:
    image: reallibrephotos/librephotos:${tag}
    restart: always
    volumes:
      - ${myPhotos}:/data
      - ${proMedia}:/protected_media
      - ${logLocation}:/logs
      - ${cachedir}:/root/.cache

    environment:
      - SECRET_KEY=${shhhhKey}
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=${dbHost}
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${mapApiKey}
      - WEB_CONCURRENCY=${gunniWorkers}
      - SKIP_PATTERNS=${skipPatterns}
      - DEBUG=0
      - HEAVYWEIGHT_PROCESS=${HEAVYWEIGHT_PROCESS}

    # Wait for Postgres
    depends_on:
      - db

  redis:
    image: redis:6
    restart: always
```

### How is you picture library mounted on the host (or in the virtual machine):
Local file system

### Description of issue:
I am running scan using the command

```
sudo docker exec --user root librephotos-docker_backend_1 python3 manage.py scan
```

The scan always stops after processing a few videos.

#### Additional Information:
Run 1
```
2021-12-10 02:41:15,423 : image_similarity.py : build_image_similarity_index : 64 : INFO : builing similarity index for user kevin
2021-12-10 02:41:15,465 : image_similarity.py : build_image_similarity_index : 90 : INFO : builing similarity index took 0.04 seconds
2021-12-10 02:41:18,190 : directory_watcher.py : is_valid_media : 41 : INFO : Could not handle /data/camera/IMG_20190818_114135_MP, because unable to call thumbnail
  VipsForeignLoad: "/data/camera/IMG_20190818_114135_MP" is not a known file format

2021-12-10 02:41:18,287 : directory_watcher.py : handle_new_image : 103 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: handling image /data/camera/PXL_20210805_225107196.TS.mp4
2021-12-10 02:41:48,395 : directory_watcher.py : handle_new_image : 121 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: generate thumbnails: /data/camera/PXL_20210805_225107196.TS.mp4, elapsed: 29.948726
2021-12-10 02:41:48,500 : directory_watcher.py : handle_new_image : 128 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: calculate aspect ratio: /data/camera/PXL_20210805_225107196.TS.mp4, elapsed: 30.053023
2021-12-10 02:41:51,086 : directory_watcher.py : handle_new_image : 103 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: handling image /data/camera/PXL_20210912_180846288.mp4
2021-12-10 02:42:26,323 : directory_watcher.py : handle_new_image : 121 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: generate thumbnails: /data/camera/PXL_20210912_180846288.mp4, elapsed: 33.903101
2021-12-10 02:42:26,427 : directory_watcher.py : handle_new_image : 128 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: calculate aspect ratio: /data/camera/PXL_20210912_180846288.mp4, elapsed: 34.006884
2021-12-10 02:42:28,664 : directory_watcher.py : handle_new_image : 103 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: handling image /data/camera/PXL_20211205_011900928.TS.mp4
2021-12-10 02:42:56,606 : directory_watcher.py : handle_new_image : 121 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: generate thumbnails: /data/camera/PXL_20211205_011900928.TS.mp4, elapsed: 27.180074
2021-12-10 02:42:56,708 : directory_watcher.py : handle_new_image : 128 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: calculate aspect ratio: /data/camera/PXL_20211205_011900928.TS.mp4, elapsed: 27.282521
2021-12-10 02:42:58,874 : directory_watcher.py : handle_new_image : 103 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: handling image /data/camera/PXL_20210808_234753368.TS.mp4
2021-12-10 02:43:34,786 : directory_watcher.py : handle_new_image : 121 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: generate thumbnails: /data/camera/PXL_20210808_234753368.TS.mp4, elapsed: 35.71976
2021-12-10 02:43:34,888 : directory_watcher.py : handle_new_image : 128 : INFO : job 7c36bef2-4e7f-473d-9aee-fce09e5eb945: calculate aspect ratio: /data/camera/PXL_20210808_234753368.TS.mp4, elapsed: 35.821918
```

Run 2
```
2021-12-10 02:46:12,894 : image_similarity.py : build_image_similarity_index : 64 : INFO : builing similarity index for user kevin
2021-12-10 02:46:12,934 : image_similarity.py : build_image_similarity_index : 90 : INFO : builing similarity index took 0.04 seconds
2021-12-10 02:46:15,281 : directory_watcher.py : is_valid_media : 41 : INFO : Could not handle /data/camera/IMG_20190818_114135_MP, because unable to call thumbnail
  VipsForeignLoad: "/data/camera/IMG_20190818_114135_MP" is not a known file format

2021-12-10 02:46:15,568 : directory_watcher.py : handle_new_image : 103 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: handling image /data/camera/VID_20191017_143348.mp4
2021-12-10 02:46:29,892 : directory_watcher.py : handle_new_image : 121 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: generate thumbnails: /data/camera/VID_20191017_143348.mp4, elapsed: 14.208943
2021-12-10 02:46:29,995 : directory_watcher.py : handle_new_image : 128 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: calculate aspect ratio: /data/camera/VID_20191017_143348.mp4, elapsed: 14.312316
2021-12-10 02:46:32,349 : directory_watcher.py : handle_new_image : 103 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: handling image /data/camera/PXL_20210826_222439318.TS.mp4
2021-12-10 02:47:06,171 : directory_watcher.py : handle_new_image : 121 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: generate thumbnails: /data/camera/PXL_20210826_222439318.TS.mp4, elapsed: 33.603974
2021-12-10 02:47:06,273 : directory_watcher.py : handle_new_image : 128 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: calculate aspect ratio: /data/camera/PXL_20210826_222439318.TS.mp4, elapsed: 33.706273
2021-12-10 02:47:08,505 : directory_watcher.py : handle_new_image : 103 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: handling image /data/camera/PXL_20210924_035402504.TS.mp4
2021-12-10 02:47:35,779 : directory_watcher.py : handle_new_image : 121 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: generate thumbnails: /data/camera/PXL_20210924_035402504.TS.mp4, elapsed: 20.65566
2021-12-10 02:47:35,883 : directory_watcher.py : handle_new_image : 128 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: calculate aspect ratio: /data/camera/PXL_20210924_035402504.TS.mp4, elapsed: 20.759281
2021-12-10 02:47:38,120 : directory_watcher.py : handle_new_image : 103 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: handling image /data/camera/PXL_20210905_025216466.mp4
2021-12-10 02:47:57,626 : directory_watcher.py : handle_new_image : 121 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: generate thumbnails: /data/camera/PXL_20210905_025216466.mp4, elapsed: 19.337266
2021-12-10 02:47:57,731 : directory_watcher.py : handle_new_image : 128 : INFO : job bd07cb98-dbb1-49ea-b940-4ab755a7952a: calculate aspect ratio: /data/camera/PXL_20210905_025216466.mp4, elapsed: 19.442473
```

Run 3
```
2021-12-10 02:53:42,066 : image_similarity.py : build_image_similarity_index : 64 : INFO : builing similarity index for user kevin
2021-12-10 02:53:42,107 : image_similarity.py : build_image_similarity_index : 90 : INFO : builing similarity index took 0.04 seconds
2021-12-10 02:53:44,531 : directory_watcher.py : is_valid_media : 41 : INFO : Could not handle /data/camera/IMG_20190818_114135_MP, because unable to call thumbnail
  VipsForeignLoad: "/data/camera/IMG_20190818_114135_MP" is not a known file format

2021-12-10 02:53:44,816 : directory_watcher.py : handle_new_image : 103 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: handling image /data/camera/PXL_20210808_234716637.TS.mp4
2021-12-10 02:54:22,110 : directory_watcher.py : handle_new_image : 121 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: generate thumbnails: /data/camera/PXL_20210808_234716637.TS.mp4, elapsed: 36.666273
2021-12-10 02:54:22,213 : directory_watcher.py : handle_new_image : 128 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: calculate aspect ratio: /data/camera/PXL_20210808_234716637.TS.mp4, elapsed: 36.769545
2021-12-10 02:54:24,583 : directory_watcher.py : handle_new_image : 103 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: handling image /data/camera/PXL_20211204_020201141.TS.mp4
2021-12-10 02:54:49,868 : directory_watcher.py : handle_new_image : 121 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: generate thumbnails: /data/camera/PXL_20211204_020201141.TS.mp4, elapsed: 24.902342
2021-12-10 02:54:49,984 : directory_watcher.py : handle_new_image : 128 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: calculate aspect ratio: /data/camera/PXL_20211204_020201141.TS.mp4, elapsed: 25.01814
2021-12-10 02:54:52,704 : directory_watcher.py : handle_new_image : 103 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: handling image /data/camera/PXL_20210802_235009608.mp4
2021-12-10 02:55:28,539 : directory_watcher.py : handle_new_image : 121 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: generate thumbnails: /data/camera/PXL_20210802_235009608.mp4, elapsed: 34.367732
2021-12-10 02:55:28,641 : directory_watcher.py : handle_new_image : 128 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: calculate aspect ratio: /data/camera/PXL_20210802_235009608.mp4, elapsed: 34.470744
2021-12-10 02:55:30,938 : directory_watcher.py : handle_new_image : 103 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: handling image /data/camera/PXL_20210907_020720566.mp4
2021-12-10 02:56:17,424 : directory_watcher.py : handle_new_image : 121 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: generate thumbnails: /data/camera/PXL_20210907_020720566.mp4, elapsed: 45.601018
2021-12-10 02:56:17,527 : directory_watcher.py : handle_new_image : 128 : INFO : job 831f149c-99d5-495c-8f94-850e556346f5: calculate aspect ratio: /data/camera/PXL_20210907_020720566.mp4, elapsed: 45.704092
```

**Comment by derneuere** [comment]
This looks to me like the same issue as #363

I changed out the dependencies for the arm images. The image is only in about an hour. Could you test it, if it now works?

To update your docker images, follow this guide:
https://docs.librephotos.com/1/updating/

**Comment by kyangk** [comment]
I am still seeing the same behavior. 


Am I still using old images? I only see frontend updated.

```
$ docker images --digests reallibrephotos/*
REPOSITORY                             TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
reallibrephotos/librephotos-frontend   dev                 sha256:9a0ec29f6f604b0b4d1eb370f74aee9db6d906bf09d1481b8f84631cfa3183f7   f87f29e9f07f        15 hours ago        31.2MB
reallibrephotos/librephotos-frontend   <none>              sha256:2da555ca5187e968861f5bc27690de43f2b3f65210d0400f7a12a9318053d86b   dfaa68898bb3        5 days ago          31.2MB
reallibrephotos/librephotos            dev                 sha256:8d8af787c4b8fa6c0fcf82ebff6db7d3711d233e28ecd08120bdc6be5853c0e8   293447f75370        11 days ago         5.83GB
reallibrephotos/librephotos-proxy      dev                 sha256:81d695c5a1b3f1165d65131c065b9fc381085b70a8ac3f54c6eb0330db4d1435   3ef16f9d6e4f        3 months ago        126MB
```

**Comment by kyangk** [comment]
I go the new image. Seems like it is completely broken now. Error on boot.

```
$ docker images --digests reallibrephotos/*
REPOSITORY                             TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
reallibrephotos/librephotos            dev                 sha256:d15b9a27add733fb0004706e2d6ba2621c96014a2ec2f7f0e0f32ee0f0686fec   ec7543958956        2 hours ago         5.78GB
reallibrephotos/librephotos-frontend   dev                 sha256:9a0ec29f6f604b0b4d1eb370f74aee9db6d906bf09d1481b8f84631cfa3183f7   f87f29e9f07f        17 hours ago        31.2MB
reallibrephotos/librephotos-frontend   <none>              sha256:2da555ca5187e968861f5bc27690de43f2b3f65210d0400f7a12a9318053d86b   dfaa68898bb3        5 days ago          31.2MB
reallibrephotos/librephotos            <none>              sha256:8d8af787c4b8fa6c0fcf82ebff6db7d3711d233e28ecd08120bdc6be5853c0e8   293447f75370        11 days ago         5.83GB
reallibrephotos/librephotos-proxy      dev                 sha256:81d695c5a1b3f1165d65131c065b9fc381085b70a8ac3f54c6eb0330db4d1435   3ef16f9d6e4f        3 months ago        126MB
```

```
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/code/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/code/api/models/photo.py", line 22, in <module>
    from api.thumbnails import (
  File "/code/api/thumbnails.py", line 5, in <module>
    from wand.image import Image
  File "/usr/local/lib/python3.8/dist-packages/wand/image.py", line 18, in <module>
    from . import assertions
  File "/usr/local/lib/python3.8/dist-packages/wand/assertions.py", line 155, in <module>
    from .color import Color  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/wand/color.py", line 10, in <module>
    from .api import library
  File "/usr/local/lib/python3.8/dist-packages/wand/api.py", line 175, in <module>
    raise ImportError('MagickWand shared library not found.\n'
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html
[2021-12-13 02:34:07 +0000] [23] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wand/api.py", line 151, in <module>
    libraries = load_library()
  File "/usr/local/lib/python3.8/dist-packages/wand/api.py", line 140, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: ['libMagickWand-7.Q16HDRI.so.10', 'libMagickWand-7.Q16HDRI.so.10']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/ownphotos/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.8/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/code/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/code/api/models/photo.py", line 22, in <module>
    from api.thumbnails import (
  File "/code/api/thumbnails.py", line 5, in <module>
    from wand.image import Image
  File "/usr/local/lib/python3.8/dist-packages/wand/image.py", line 18, in <module>
    from . import assertions
  File "/usr/local/lib/python3.8/dist-packages/wand/assertions.py", line 155, in <module>
    from .color import Color  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/wand/color.py", line 10, in <module>
    from .api import library
  File "/usr/local/lib/python3.8/dist-packages/wand/api.py", line 175, in <module>
    raise ImportError('MagickWand shared library not found.\n'
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html
[2021-12-13 02:34:07 +0000] [23] [INFO] Worker exiting (pid: 23)
[2021-12-13 02:34:07 +0000] [24] [INFO] Worker exiting (pid: 24)
```

**Comment by derneuere** [comment]
Alright, I pushed another update. It works on my Raspberry PI 3+, so it should work now for you too :)

**Comment by kyangk** [comment]
fixed with new update
