### ISSUE TITLE
rescan faces failed 

### ISSUE THREAD

**Issue by EricInBj** [LibrePhotos/librephotos#414]
### UPDATE:

the real reason is NOT OOM,   but
 ```
2021-12-29 14:08:39,894 : directory_watcher.py : scan_faces : 437 : ERROR : An error occured:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "api_face_pkey"
DETAIL:  Key (id)=(13374) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/code/api/directory_watcher.py", line 391, in face_scanner
    photo._extract_faces()
  File "/code/api/models/photo.py", line 580, in _extract_faces
    face_image.save(face_io, format="JPEG")
```

i wrap  a ``` try ... except ``` to the save code, it seems to work fine.

```
    try:
        face_image.save(face_io, format="JPEG")
        face.image.save(face.image_path, ContentFile(face_io.getvalue()))
        face_io.close()
        face.save()
    except Exception:
        logger.info(
            "image {}: rescan face failed".format(self.image_paths[0])
        )

```

### What architecture is LibrePhotos running on:
x64 

### How is LibrePhotos installed:
Docker

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (EXT4)

### My LibrePhotos env overview:

Data amount: 
~80000 photos
~120000 faces
~300 people

### What architecture is LibrePhotos running on:
x64 

### How is LibrePhotos installed:
Docker

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (EXT4)

### My LibrePhotos env overview:
Hardware: HP Microserver Gen10 plus (E2224 / 16G), SSD
System: Ubuntu 20.04 with 10GB RAM (ESXi VM), run librephotos with docker.

Data amount: 
~80000 photos
~120000 faces
~300 people

### Description of issue:
rescan faces will failed quickly.
when start a "rescan faces" job,  the backend's memory usage increased very fast,  until OOM, then job failed.  
<img width="1395" alt="rescan_faces_oom" src="https://user-images.githubusercontent.com/1046818/147619233-02a6f31d-7440-436a-9af6-b74cef1438b9.png">

**Comment by derneuere** [comment]
I addressed the issue in commit: https://github.com/LibrePhotos/librephotos/commit/7bfa784fba6eb541e4a6ff90eb45780dbc45e804

When extracting faces with multiple processes, it can happen, that two processes save at the same time, which leads
to an integrety error. We will now log this error and then try again once.

How many HEAVYWEIGHT_PROCESS have you configured and could you try it again?

**Comment by EricInBj** [comment]
My config: HEAVYWEIGHT_PROCESS=4

I have tried again, i think the ``` duplicate key ``` error is FIXED, THANK YOU.

And, i get another error after scanning for some hours:

```
2021-12-31 00:40:20,120 : directory_watcher.py : scan_faces : 434 : ERROR : An error occured:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/code/api/directory_watcher.py", line 391, in face_scanner
    photo._extract_faces()
  File "/code/api/models/photo.py", line 531, in _extract_faces
    image = np.array(PIL.Image.open(self.thumbnail_big.path))
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/protected_media/thumbnails_big/fc9948ca9ad097028a607b7cfa4e44941.webp'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 431, in scan_faces
    pool.starmap(face_scanner, all)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/protected_media/thumbnails_big/fc9948ca9ad097028a607b7cfa4e44941.webp'
2021-12-31 00:40:20,375 : directory_watcher.py : scan_faces : 438 : INFO : Added 4464 faces
```

**Comment by EricInBj** [comment]
> When extracting faces with multiple processes, it can happen, that two processes save at the same time

multiple processes working on the same photo?  the ``` duplicate key``` error really happens frequently。

**Comment by derneuere** [comment]
It's now wrapped into it's own process. Should not happen anymore.
