### ISSUE TITLE
Remove photos fail if photo is reference as cover

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#424]
### What Operating system and version is LibrePhotos running on:
Ubuntu, and librephotos dev

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### Description of issue:
If a cover photo is 'deleted' or moved it cannot delete it.

### How can we reproduce it:
delete a cover photo from a person.

#### Additional Information:
```
2022-01-15 13:03:56,888 : api_util.py : get_search_term_examples : 173 : INFO : Found 100 photos
2022-01-15 13:04:28,774 : autoalbum.py : delete_missing_photos : 202 : ERROR : An error occured
Traceback (most recent call last):
  File "/code/api/autoalbum.py", line 195, in delete_missing_photos
    missing_photos.delete()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 746, in delete
    collector.collect(del_query)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Photo' because they are referenced through protected foreign keys: 'Person.cover_photo'.", {<Person: 105>, <Person: 60>, <Person: 53>, <Person: 14>})
```
![image](https://user-images.githubusercontent.com/29661633/149623308-cd7ed85f-e60c-46ca-a032-0185d8b0ca55.png)

**Comment by derneuere** [comment]
This will be fixed in the next release :)

**Comment by Nerodacles** [comment]
You're doing god's work.
