### ISSUE TITLE
Viz/Face Clusters / Timeline stuck on loading animation

### ISSUE THREAD

**Issue by MultiCoreNop** [LibrePhotos/librephotos#427]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [X] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Linux 5.15

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
LibrePhotos 3.8
docker-compose 1.29.2

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (ext4)

### Description of issue:
Viz/Face cluster shows the "loading ring" animation - even one hour later. While in the middle of the inital scanning it was able to show the graphic, but now after scanning is complete it just "loads" (restarting everything did not resolve the issue).

Same is happening on Viz/Timeline. The histogram does show, but the timeline has a loading animation (waited for ~20min).

While loading animation is shown, there is no real CPU usage from LibrePhotos, so I do not think that it is actually doing something.

### How can we reproduce it:
I did:
1. fresh install
2. initial scan
3. issue shows
(but I don't know how reproducible that is)

While reloading the page on 'face clusters' the following gets added to ownphotos.log:
```
2022-01-20 14:17:04,224 : api_util.py : get_search_term_examples : 159 : INFO : 100 possible ids
2022-01-20 14:17:04,225 : api_util.py : get_search_term_examples : 172 : INFO : Getting search terms for user 1
2022-01-20 14:17:04,279 : api_util.py : get_search_term_examples : 173 : INFO : Found 100 photos
2022-01-20 14:17:04,408 : api_util.py : get_search_term_examples : 159 : INFO : 100 possible ids
2022-01-20 14:17:04,409 : api_util.py : get_search_term_examples : 172 : INFO : Getting search terms for user 1
2022-01-20 14:17:04,462 : api_util.py : get_search_term_examples : 173 : INFO : Found 100 photos
```

In gunicorn_django.log:
```
Unauthorized: /api/searchtermexamples/
```

No other log is being touched.

### Viz / Timeline ###
Here the logs are more interesting. gunicorn_django.log:
```
Unauthorized: /api/searchtermexamples/
Internal Server Error: /api/locationtimeline/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/api/views/views.py", line 1108, in get
    res = get_location_timeline(request.user)
  File "/code/api/api_util.py", line 92, in get_location_timeline
    current_page = [
  File "/code/api/api_util.py", line 93, in <listcomp>
    (p.exif_timestamp, p.geolocation_json["features"][-1]["text"])
IndexError: list index out of range
```

(added entries in ownphotos.log are identical to timeline reload)

**Comment by derneuere** [comment]
The issue was, that no data was found. Now it behaves better :)

**Comment by MultiCoreNop** [comment]
Loading does indeed stop now.
Yet, on "location timeline" is simply says "no data" and on face clusters "no faces".

**Comment by derneuere** [comment]
Do you have faces and locations? You can only get locations if you configured mapbox afaik

**Comment by loulou91** [comment]
I confirm the bug which is there since a long time ;-)

**Comment by MultiCoreNop** [comment]
Under settings it shows:
95424
Photos
54
People
66813
Faces

While it was scanning for the first time, those "charts" were actually populated.
