### ISSUE TITLE
Clip embeddings crashes when it does not have any images

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#430]
Clip embeddings crashes if you try to scan 0 images.
```
librephotos-docker-backend-1   | ERROR:ownphotos:job aae8e01b-ba13-4750-8109-13b46ff20753: could not load image /data/sample-images-master/Samples/TIF/marbles.tif. reason: unsupported operand type(s) for /: 'NoneType' and 'NoneType'
librephotos-docker-backend-1   | Traceback (most recent call last):
librephotos-docker-backend-1   |   File "/code/api/directory_watcher.py", line 126, in handle_new_image
librephotos-docker-backend-1   |     photo._calculate_aspect_ratio(False)
librephotos-docker-backend-1   |   File "/code/api/models/photo.py", line 352, in _calculate_aspect_ratio
librephotos-docker-backend-1   |     self.image_paths[0],
```

**Comment by Rihcus** [comment]
```
/code/api/directory_watcher.py:369: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.photo.Photo'> QuerySet.
  paginator = Paginator(exisisting_photos, 5000)
18:34:10 default: Job OK (78e82e94-79e1-4eed-ab57-2857090fa2df)
18:34:10 Result is kept for 60 seconds
18:34:10 default: api.batch_jobs.batch_calculate_clip_embedding(UUID('aba951a4-e41c-49a4-bec5-c444b5a8a48e'), <User: rihcus>) (e5633f87-511e-415d-8137-ac7bb4ac7b81)
/usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py:287: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
18:34:48 Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)
18:41:33 Cleaning registries for queue: default
```
Not sure if this is related:
![image](https://user-images.githubusercontent.com/30292597/151748212-211a922d-3d1b-4a45-a341-e76fa29f9ff5.png)

Clip embedings get stuck and logs indicate worker is crashing due to InterpolationMode
