### ISSUE TITLE
Filename Error?

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#475]
## 🐛 Bug Report
* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.04.4 LTS x64
docker-compose version 1.29.2, build 5becea4c
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
Librephotos:dev

### Description of issue:
Doing a scan just throws this error:

```
ERROR:ownphotos:job 1ff72444-5028-478c-9795-db6d54063fe5: could not load image /data/neroData/2021-03-21 13.41.20.mp4. reason: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 232, in rescan_image
    photo._geolocate_mapbox(True)
  File "/code/api/models/photo.py", line 389, in _geolocate_mapbox
    new_gps_lat, new_gps_lon = get_metadata(
  File "/code/api/util.py", line 138, in get_metadata
    retrieved_value = et.get_tag(tag, file)
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 647, in get_tag
    return self.get_tag_batch(tag, [filename])[0]
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 630, in get_tag_batch
    data = self.get_tags_batch([tag], filenames)
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 595, in get_tags_batch
    return self.execute_json(*params)
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 539, in execute_json
    return json.loads(res_decoded)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

And i checked, the video is ok, it isn't corrupt o smt like that.

### How can we reproduce it:
Don't know, maybe it is the path?

#### Additional Information:
* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by derneuere** [comment]
Can't reproduce, was probably fixed along the way.
