### ISSUE TITLE
Can't Add New Users

### ISSUE THREAD

**Issue by masmith79** [LibrePhotos/librephotos#476]
Greetings:

My setup is as follows: LibrePhotos running in an Ubuntu 20.04 LXC container on a ProxMox host via the [manual install](https://docs.librephotos.com/1/manual_debian_install/) .  I am able to navigate to the website and I believe I set up the admin account properly however, when I want to add a non-admin user via the "Sign Up" feature, nothing happens.  Running a tail on `/var/log/librephotos/gunicorn_django.log` I get this

On clicking Sign Up:
`WARNING:django.request:Unauthorized: /api/rqavailable/`

When I click "Sign Up" (after entering all the requested info) I get:
```
Internal Server Error: /api/user/
Traceback (most recent call last):
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/librephotos/backend/api/serializers/user.py", line 95, in create
    user = User.objects.create_superuser(**validated_data)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 155, in create_superuser
    raise ValueError('Superuser must have is_superuser=True.')
ValueError: Superuser must have is_superuser=True.
Unauthorized: /api/rqavailable/
```
Any assistance would be greatly appreciated;  thank you!

**Comment by derneuere** [comment]
I fixed it. Do a git pull in the librephotos backend code folder to update it :smile:
