### ISSUE TITLE
Video playback black/transparent in "Photos" tab

### ISSUE THREAD

**Issue by imwhocodes** [LibrePhotos/librephotos#477]
Hi

I'm having some problem opening videos in the main page (Photos with timestamp and Photos Recently Added)

The video preview (when you hover with the mouse over it) work correctly, but if you click on it the media start playing, audio is reproduced but there is no video
The carusel/player itself open correctly but it stay as a semi-transparent (gray/black) overlay
You can scroll back and forth on the video but no image is displayed

Tested with docker-compose installation with both releases week 11-12 and week 13, client side tested with various macos/chrome and Ubuntu/Firefox

If you play the same video from Albums Places page it work correctly

Thank you for this wonderful project,
Luca

**Comment by derneuere** [comment]
It would really help me, if you could explain how you installed LibrePhotos and if you get any errors in the frontend or backend. The logs are within the specified logs folder.

This error is not reproducible yet on the demo server.

**Comment by imwhocodes** [comment]
Ok I think i found the problem

As I was suspecting it is on client side:
On some video when you open it for playback if the thumbnail is not present (I got the job **Calculate Clip Embeddings** stuck) the player is not showing the video

On the browser dev console i get `GET http://<address>/media/thumbnails_big/4257761d533710fed63d0539f1d464bd1 404 (Not Found)`

**Comment by imwhocodes** [comment]
Today I launch another full scan job, it is stuck at 0% of `Calculate Clip Embeddings`

In the logs there is this error:
```
backend     | INFO:ownphotos:Could not handle /data/_old projects/Drive train/_DS_Store, because unable to call thumbnail
backend     |   VipsForeignLoad: "/data/_old projects/Drive train/_DS_Store" is not a known file format
backend     |
backend     | ERROR:ownphotos:job 108fef20-5c02-4d56-b82d-14f7fb0870b9: could not load image /data/Barzan (2022)/unselected/IMG_1428.HEIC. reason: list index out of range
backend     | Traceback (most recent call last):
backend     |   File "/code/api/directory_watcher.py", line 234, in rescan_image
backend     |     photo._add_location_to_album_dates()
backend     |   File "/code/api/models/photo.py", line 453, in _add_location_to_album_dates
backend     |     city_name = [
backend     | IndexError: list index out of range
backend     | /code/api/directory_watcher.py:386: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.photo.Photo'> QuerySet.
backend     |   paginator = Paginator(exisisting_photos, 5000)
backend     | 09:41:55 default: Job OK (bc073fe8-b041-473a-92a1-20c20a09fa2d)
backend     | 09:41:55 Result is kept for 60 seconds
redis       | 1:M 29 Apr 2022 09:41:55.242 * 100 changes in 300 seconds. Saving...
redis       | 1:M 29 Apr 2022 09:41:55.242 * Background saving started by pid 23
redis       | 23:C 29 Apr 2022 09:41:55.246 * DB saved on disk
redis       | 23:C 29 Apr 2022 09:41:55.247 * RDB: 0 MB of memory used by copy-on-write
backend     | 09:41:55 Cleaning registries for queue: default
backend     | 09:41:55 default: api.batch_jobs.batch_calculate_clip_embedding(UUID('f0c1b4ec-2ae8-4b6b-b439-9a62ff563e65'), <User: admin>) (714d1370-292c-4cef-a418-23656b685bb8)
redis       | 1:M 29 Apr 2022 09:41:55.343 * Background saving terminated with success
backend     | /usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py:287: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
backend     |   warnings.warn(
backend     | 09:42:00 default: Job OK (714d1370-292c-4cef-a418-23656b685bb8)
backend     | 09:42:00 Result is kept for 60 seconds
backend     | 10:09:01 Cleaning registries for queue: default
backend     | 10:36:01 Cleaning registries for queue: default
redis       | 1:M 29 Apr 2022 10:41:56.092 * 1 changes in 3600 seconds. Saving...
redis       | 1:M 29 Apr 2022 10:41:56.092 * Background saving started by pid 24
redis       | 24:C 29 Apr 2022 10:41:56.097 * DB saved on disk
redis       | 24:C 29 Apr 2022 10:41:56.098 * RDB: 0 MB of memory used by copy-on-write
redis       | 1:M 29 Apr 2022 10:41:56.193 * Background saving terminated with success
backend     | 11:03:01 Cleaning registries for queue: default
backend     | 11:30:01 Cleaning registries for queue: default
redis       | 1:M 29 Apr 2022 11:41:57.092 * 1 changes in 3600 seconds. Saving...
redis       | 1:M 29 Apr 2022 11:41:57.092 * Background saving started by pid 25
redis       | 25:C 29 Apr 2022 11:41:57.096 * DB saved on disk
redis       | 25:C 29 Apr 2022 11:41:57.096 * RDB: 0 MB of memory used by copy-on-write
redis       | 1:M 29 Apr 2022 11:41:57.192 * Background saving terminated with success
backend     | 11:57:01 Cleaning registries for queue: default
backend     | 12:24:01 Cleaning registries for queue: default
redis       | 1:M 29 Apr 2022 12:41:58.057 * 1 changes in 3600 seconds. Saving...
redis       | 1:M 29 Apr 2022 12:41:58.057 * Background saving started by pid 26
redis       | 26:C 29 Apr 2022 12:41:58.061 * DB saved on disk
redis       | 26:C 29 Apr 2022 12:41:58.061 * RDB: 0 MB of memory used by copy-on-write
redis       | 1:M 29 Apr 2022 12:41:58.158 * Background saving terminated with success
backend     | 12:51:02 Cleaning registries for queue: default
backend     | Unauthorized: /api/rqavailable/
```

Thanks,
Luca

**Comment by varet80** [comment]
I have similar issue. 

The Playback is not working on both Chrome and Firefox!
I installed it using docker in multiple instances.

Some things I found are:
1. The thumbnail link is a jpg 
2. Download and/or the link on right side same - 
3. the video link is broken - 404 - https://priv_url/media/video/7889d602e1a70697f1e7aefd906fb5682


The Nginx snippet for media is:
```
    location ~ ^/(api|media)/ {
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host librephotos-backend;
      include uwsgi_params;
      proxy_pass http://librephotos-backend;
    }
```

Preview of Video works! but not the video itself! Also Download is not working on Videos only.

**Comment by imwhocodes** [comment]
The other day I noticed that if you put:

```
**Experimental options**
Always transcode videos : **_On_**
```

The problematics video start to playback again correctly, the problem is that transcoding is very heavy and video is unplayable (lagging and shuttering)

**Comment by derneuere** [comment]
This is related to this issue here: https://github.com/LibrePhotos/librephotos/issues/365

It would make sense for low powered machines to add a transcoding option that saves on disk instead.
