### ISSUE TITLE
Auto Scan does not work

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#550]
We have the issue that the auto scan is not working, because it can't get the secret key. Some users added a secret key by themselves #25  This is not preferred as we use the secret.key file instead and this key should be the same over all backend processes.

**Comment by Fonsos** [comment]
I had a working instalation in Unraid with docker, but I had it in a wrong folder and I wanted to start form 0 so I have installed it again and now the auto scan script doesn't work.

I have the same issue that in the named issue, but I have seen that when I get the system up the shhhhKey is blank because we don't configure it in the .env file anymore.

Maybe this information can help to solve this issue, if not, I'll delete this comment, to keep this clean.

![image](https://user-images.githubusercontent.com/9643213/182117935-47f138a3-5f12-4cee-8efc-f9352906d9ad.png)

**Comment by kuzmos** [comment]
EDIT: disregard please, `docked pull` to the latest resolved the problem.

This is what is shown for me:

```
sudo /usr/bin/docker exec --user root librephotos_backend_1 python3 manage.py scan
Traceback (most recent call last):
  File "/code/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/code/api/management/commands/scan.py", line 34, in handle
    scan_photos(user, options["full_scan"], uuid.uuid4())
TypeError: scan_photos() missing 1 required positional argument: 'scan_directory'
```

**Comment by derneuere** [comment]
This is now implemented.
