### ISSUE TITLE
Docker Auto Scan

### ISSUE THREAD

**Issue by nanoby7e** [LibrePhotos/librephotos#587]
### What Operating system and version is LibrePhotos running on:
CentOS 8

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker Compose version v2.7.0

### Are you running LibrePhotos on a virtual machine if so please list:
Yes

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB
SMB

### Description of issue:
Following the documentation for Auto Scan All Folders (https://docs.librephotos.com/2/auto_scan/), there is no scan option available in the script. When I run the manage.py script per the documentation, it returns an error:

`sudo docker exec --user root backend python3 manage.py scan
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 224, in fetch_command
    app_name = commands[subcommand]
KeyError: 'scan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.9/dist-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/dist-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/dist-packages/django/conf/__init__.py", line 189, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.`

When I run from inside the backend image, here are my options:

`python3 manage.py 

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    runserver
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver
Note that only Django core commands are listed as settings are not properly configured (error: The SECRET_KEY setting must not be empty.).
`

#### Additional Information:

No additional comments on the bug, but can a feature be added into the web app to schedule regular file system scans for new images?

**Comment by yassendobrev** [comment]
You need to generate a Django secret key for example using [this](https://miniwebtool.com/django-secret-key-generator/) and set `shhhhKey` in `.env` to it.

Example:
```
shhhhKey="5bf!b_ebppb6a3n%e#+s&#og%fyyxz@@h_=m@xazqjxuvc=lg+"
```

**Comment by Teonyr** [comment]
I'm having the same problem as the creator of this issue.

Sadly the approach mentioned above doesn't work for me:

If I generate a "Django secret key" and add it to my .yml/.env, like mentioned above, I receive some error messages in the log and am unable to log in to / use librephotos at all.

```
Internal Server Error: /api/auth/token/obtain/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django_cryptography/core/signing.py", line 237, in unsign
    self.signature(signed_value[:-d_size]).verify(sig)
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/primitives/hmac.py", line 72, in verify
    ctx.verify(signature)
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/backends/openssl/hmac.py", line 85, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/ownphotos/urls.py", line 70, in post
    response = super(TokenObtainPairView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/views.py", line 27, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/serializers.py", line 70, in validate
    data = super().validate(attrs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/serializers.py", line 49, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.9/dist-packages/django/contrib/auth/backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/local/lib/python3.9/dist-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 70, in __iter__
    for row in compiler.results_iter(results):
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1100, in apply_converters
    value = converter(value, expression, connection)
  File "/usr/local/lib/python3.9/dist-packages/django_cryptography/fields.py", line 173, in from_db_value
    return self._load(force_bytes(value))
  File "/usr/local/lib/python3.9/dist-packages/django_cryptography/fields.py", line 115, in _load
    return pickle.loads(self._fernet.decrypt(value, self.ttl))
  File "/usr/local/lib/python3.9/dist-packages/django_cryptography/utils/crypto.py", line 143, in decrypt
    data = self._signer.unsign(data, ttl)
  File "/usr/local/lib/python3.9/dist-packages/django_cryptography/core/signing.py", line 239, in unsign
    raise BadSignature(
django.core.signing.BadSignature: Signature "b'w0+WVejHSNvm5AFXUKcwbMcPQ6Oyc60xgsaxUQ2sLbw=\n'" does not match
```

Removing the newly generated secret key (and therefore leaving it blank again) makes librephotos usable again but also reintreduces the first issue.

**Comment by derneuere** [comment]
The issue is that it can't get the secret key from the file. Adding a secret key by themselves is not a good idea, because the key should be the same over all backend processes. The docker exec command should get pulled from secret.key file in the log folder instead, and it's not yet clear, why the secret does not get pulled when using docker exec.

**Comment by seidler2547** [comment]
I solved it like this for now: `docker compose exec --user root backend bash -c 'SECRET_KEY="$(cat /logs/secret.key)" python3 manage.py scan'`

**Comment by nanoby7e** [comment]
Awesome! I'm rebuilding some vm's tonight, I'll retest it.

**Comment by Teonyr** [comment]
> I solved it like this for now: `docker compose exec --user root backend bash -c 'SECRET_KEY="$(cat /logs/secret.key)" python3 manage.py scan'`

For the time being, this works for me. :)

**Comment by derneuere** [comment]
This will be fixed by the next release :) I will do a release this or next Tuesday, depending on how far I get with the face / person refactoring,
