### ISSUE TITLE
KeyError when trying to "Find Similar Faces"

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#607]
## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues, including closed ones.

### What Operating system and version is LibrePhotos running on:
Manjaro

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker-Compose on dev tag

### How is your picture library mounted on the host (or in the virtual machine):
Local file system 

### Description of issue:

I used both the first version and the newest clustering versions on my production system. When using the latest version, it creates the clusters, but is not able to add the encoding, because of a key error.

```
2022-08-15 11:48:52,079 : face_classify.py : cluster_all_faces : 100 : ERROR : An error occurred
Traceback (most recent call last):
  File "/code/api/face_classify.py", line 86, in cluster_all_faces
    target_count: int = create_all_clusters(user, lrj)
  File "/code/api/face_classify.py", line 161, in create_all_clusters
    new_clusters: list[Cluster] = ClusterManager.try_add_cluster(
  File "/code/api/cluster_manager.py", line 127, in try_add_cluster
    encoding_by_person[closest_cluster.person.id].append(encoding)
KeyError: 1
```

### How can we reproduce it:

Use the old version, update, rerun on the new version

**Comment by derneuere** [comment]
@jakekapellen Maybe you could have a look? 😅
