### ISSUE TITLE
Can't import RAW (.NEF) files

### ISSUE THREAD

**Issue by dotter-ak** [LibrePhotos/librephotos#634]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I've istalled LibrePhotos via Unraid community app and found an issue - my RAW photos (.NEF) cant be imported.
.JPG files imported without any issues.
In [logs](https://github.com/LibrePhotos/librephotos/files/9533675/logs.zip) I've found this:

```
2022-09-09 07:57:19,352 : directory_watcher.py : handle_new_image : 116 : INFO : job ab02c651-20e8-4f3e-a284-5a933fc5a79e: handling image /var/lib/librephotos/photos/DSC_0002.NEF
2022-09-09 07:57:19,726 : directory_watcher.py : handle_new_image : 227 : ERROR : job ab02c651-20e8-4f3e-a284-5a933fc5a79e: could not load image /var/lib/librephotos/photos/DSC_0002.NEF. reason: unable to open image `/tmp/magick-WpfCSCvAtEIYR23rVWV6lpZ7dpoYZzJK.ppm': No such file or directory @ error/blob.c/OpenBlob/2924
Traceback (most recent call last):
  File "/usr/lib/librephotos/backend/api/directory_watcher.py", line 132, in handle_new_image
    photo._generate_thumbnail(True)
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 244, in _generate_thumbnail
    createThumbnail(
  File "/usr/lib/librephotos/backend/api/thumbnails.py", line 60, in createThumbnail
    with Image(filename=inputPath) as img:
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/wand/image.py", line 9110, in __init__
    self.read(filename=filename)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/wand/image.py", line 9705, in read
    self.raise_exception()
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.BlobError: unable to open image `/tmp/magick-WpfCSCvAtEIYR23rVWV6lpZ7dpoYZzJK.ppm': No such file or directory @ error/blob.c/OpenBlob/2924
```

**Comment by rmu75** [comment]
Have the same issue with sony .ARWs, manual install, ubuntu 20.04 lts.

**Comment by rmu75** [comment]
It seems imagemagick is confured to call `ufraw-batch` to convert raw-files. I could not find current packages, but I was able to install debian packages of `ufraw-batch`, `libjpeg62-turbo` and `libexiv2_14` from buster. Seems to work now.
