### ISSUE TITLE
subjectDictance with value "undef"

### ISSUE THREAD

**Issue by ajcarrascod** [LibrePhotos/librephotos#666]
When scan a photo with metadata value not valid, there is an error. I have a photo with the field  'subjectDistance' with the value that is not a float.

The error log:

-----
2022-10-16 08:48:17,417 : directory_watcher.py : rescan_image : 255 : ERROR : job c58d0a84-cf7d-4d90-8768-107ba5cea573: could not load image /data/uploads/web/IMG_20150313_163656.jpg. reason: Field 'subjectDistance' expected a number but got 'undef'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/fields/__init__.py", line 1687, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 'undef'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 246, in rescan_image
    photo._extract_exif_data(True)
  File "/code/api/models/photo.py", line 542, in _extract_exif_data
    self.save()
  File "/code/api/models/photo.py", line 135, in save
    return super().save(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 872, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 926, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 803, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1522, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1143, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1488, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/fields/__init__.py", line 823, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/fields/__init__.py", line 818, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/fields/__init__.py", line 1689, in get_prep_value
    raise e.__class__(
ValueError: Field 'subjectDistance' expected a number but got 'undef'.
-----

**Comment by ajcarrascod** [comment]
thanks :smiley:
