### ISSUE TITLE
Scan worker dont finish successfully even with one picture

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#728]
All detailed information are in the attached file to understand and to reproduce the issue (.env .yml and the whole librephotos directory). 2023/01/16 dev pull is used.

When I scan a picture, the worker "scan photo" ends without green tag but with red circle. The ownphotos log  terminates with
`ERROR : An error occurred: 
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 382, in scan_photos
    existing_photo._check_files()
  File "/code/api/models/photo.py", line 668, in _check_files
    for file in self.files:
TypeError: 'ManyRelatedManager' object is not iterable
2023-01-16 19:44:29,693 : directory_watcher.py : scan_photos : 390 : INFO : Added 1 photos
2023-01-16 19:44:29,835 : face_classify.py : train_faces : 243 : INFO : No labeled faces found`
However, the picture looks to be correctly scanned.
Hope this helps.
[LP issue.zip](https://github.com/LibrePhotos/librephotos/files/10429448/LP.issue.zip)

**Comment by loulou91** [comment]
Looks corrected with today pool... The only update seems to be redis...
![image](https://user-images.githubusercontent.com/51127123/213213002-9dd509f4-50dd-4ca5-a595-3ed5c303b521.png)
Well, I close and will have a look if it comes again.
