### ISSUE TITLE
Scan job exits with exception Internal Server Error: /api/jobs/

### ISSUE THREAD

**Issue by atlas-shrugged08** [LibrePhotos/librephotos#787]
# 🐛 Bug Report

* [ x] 📁 I've Included a ZIP file containing my librephotos `log` files
* * [Archive.zip](https://github.com/LibrePhotos/librephotos/files/10958549/Archive.zip)
* [ x] ❌ I have looked for similar issues (including closed ones)
* [ na] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Scan job exits with exception, has happened twice in a row. (after scanning about 50k photos).

exception, first:
```
EOS 60D/2014-05-03_225418_Canon EOS 60D_IMG_0284.jpg, elapsed: 18.202155
2023-03-12 19:41:35 INFO:ownphotos:job 5a1cdbce-65ba-44bf-9928-80e2de83a397: handling image /data/Family/Pics/2014/05-May/Canon EOS 60D/2014-05-03_225426_Canon EOS 60D_IMG_0285.jpg
2023-03-12 19:42:09 Internal Server Error: /api/jobs/
2023-03-12 19:42:09 Traceback (most recent call last):
2023-03-12 19:42:09   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
2023-03-12 19:42:09     return self.cursor.execute(sql, params)
2023-03-12 19:42:09 psycopg2.OperationalError: server closed the connection unexpectedly
2023-03-12 19:42:09     This probably means the server terminated abnormally
2023-03-12 19:42:09     before or while processing the request.
2023-03-12 19:42:09 
2023-03-1
```

exception, second time:
```
2023-03-13 08:38:36 INFO:ownphotos:job c9a6af64-d59f-49d0-a38f-9667251a4651: extract video length: /data/Family/Pics/2013/07-July/Canon EOS 60D/2013-07-06_063056_Canon EOS 60D_IMG_4666.jpg, elapsed: 49.146051
2023-03-13 08:38:53 Internal Server Error: /api/rqavailable/
2023-03-13 08:38:53 Traceback (most recent call last):
2023-03-13 08:38:53   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
2023-03-13 08:38:53     return self.cursor.execute(sql, params)
2023-03-13 08:38:53 psycopg2.OperationalError: server closed the connection unexpectedly
2023-03-13 08:38:53     This probably means the server terminated abnormally
2023-03-13 08:38:53     before or while processing the request.
2023-03-13 08:38:53 
2023-03-13 08:38:53
```

## 🔁 How can we reproduce it:

Not sure, seems specific to my instance?

## Please provide additional information:
- 💻 Operating system: macos ventura
- ⚙ Architecture (x86 or ARM): M1
- 🔢 Librephotos version: latest from 17 days back docker pull reallibrephotos/librephotos:latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: 84f9c8087440
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): USB
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):  NA

**Comment by derneuere** [comment]
Updated to pytorch 2.0.1. Should fix the error in dev and will be available in the next latest release.
