### ISSUE TITLE
Physical file deletion is not working

### ISSUE THREAD

**Issue by jchnkl** [LibrePhotos/librephotos#802]
This might be related to #801 . The setup is the same: Stock dockerfile from the repository.

After moving a file to trash (= marking it as deleted) I try to physically delete it from the trash.

The backend fails to delete the file from the library. It's still in the trash folder but gone from the file system. I tried running the "Remove missing photos" action but the photo still shows up in the trash folder afterwards.

As in #801 I also removed the `scanDirectory` and used `docker cp` + rescan to inject a file to the container, but the error persists.

```
backend     | Internal Server Error: /api/photosedit/delete
backend     | Traceback (most recent call last):
backend     |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
backend     |     response = get_response(request)
backend     |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
backend     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend     |   File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
backend     |     return view_func(*args, **kwargs)
backend     |   File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 70, in view
backend     |     return self.dispatch(request, *args, **kwargs)
backend     |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
backend     |     response = self.handle_exception(exc)
backend     |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
backend     |     self.raise_uncaught_exception(exc)
backend     |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
backend     |     raise exc
backend     |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
backend     |     response = handler(request, *args, **kwargs)
backend     |   File "/code/api/views/photos.py", line 517, in delete
backend     |     photo.manual_delete()
backend     |   File "/code/api/models/photo.py", line 705, in manual_delete
backend     |     file.delete()
backend     |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 946, in delete
backend     |     collector.collect([self], keep_parents=keep_parents)
backend     |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/deletion.py", line 302, in collect
backend     |     raise ProtectedError(
backend     | django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'File' because they are referenced through protected foreign keys: 'Photo.main_file'.", {<Photo: 59047fbcae59fc1d77b8eb87cf6b0d741>})
```

I obtained a DB dump before and after:

```
[!23694 $] docker cp test.jpg backend:/data

[!23695 $] docker exec -ti backend ls -la /data
total 1416
drwxr-xr-x 1 root root      16 Mar 27 10:17 .
drwxr-xr-x 1 root root     276 Mar 27 10:17 ..
-rw-r--r-- 1 1000  142 1448246 Mar 27 10:11 test.jpg

[!23696 $] docker exec -ti db pg_dump -U docker -d librephotos > db_dump_after_file_injection.txt

# marked file as deleted and tried to empty the trash

[!23699 $] docker exec -ti backend ls -la /data
total 0
drwxr-xr-x 1 root root   0 Mar 27 10:18 .
drwxr-xr-x 1 root root 276 Mar 27 10:17 ..

[!23698 $] docker exec -ti db pg_dump -U docker -d librephotos > db_dump_after_delete_fail.txt   
```

[db_dump_after_file_injection.txt](https://github.com/LibrePhotos/librephotos/files/11077458/db_dump_after_file_injection.txt)
[db_dump_after_delete_fail.txt](https://github.com/LibrePhotos/librephotos/files/11077459/db_dump_after_delete_fail.txt)

**Comment by derneuere** [comment]
Pushed a fix to handle deletion correctly :)
