### ISSUE TITLE
Scan Photos (integer out of range)

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#805]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I just did a rescan.

## 🔁 How can we reproduce it:

```
ERROR:ownphotos:job 907b424b-b9ae-40b0-9ec3-6dd601cdf80c: could not load image /data/neroData/Camera/2021/05/VID_20210516_165624671.mp4. reason: integer out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 216, in rescan_image
    photo._extract_exif_data(True)
  File "/code/api/models/photo.py", line 537, in _extract_exif_data
    self.save()
  File "/code/api/models/photo.py", line 140, in save
    return super().save(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 872, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 926, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 803, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1522, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range
```

## Please provide additional information:
- 💻 Operating system: Ubuntu 20.04
- ⚙ Architecture (x86 or ARM):  x86
- 🔢 Librephotos version: dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker-compose
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): NFS
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): Hyper-V

**Comment by nickdrones** [comment]
I am still having this same issue

**Comment by derneuere** [comment]
@nickdrones It would be great if you could also fill out the bug report template.
