### ISSUE TITLE
Scan crashes on character '\udceb' 

### ISSUE THREAD

**Issue by Chacsam** [LibrePhotos/librephotos#828]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

After a fresh docker install on Ubuntu (using host PostgresQL & Redis) I have been gradually scanning and adding pictures. (One year at a time)
The first 5.000-ish went ok. Third scan with an additional batch stopped before the end.

I tried to redorun the scan with 1 worker in order to see if I could locate a problematic file, but no luck.

Log Finishing on the following.

```

`2023-04-17 15:33:01,646 : directory_watcher.py : handle_new_image : 193 : WARNING : job 1e9d3256-2a30-4da4-ac6c-064e90e46960: file /data/valerie/2021/2021 12/d7ca2b29-6792-4615-9781-b432de4f7403.jpg exists already
2023-04-17 15:33:08,870 : directory_watcher.py : scan_photos : 386 : ERROR : An error occurred: 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/code/api/directory_watcher.py", line 261, in photo_scanner
    if Photo.objects.filter(files__path__contains=path).exists():
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 537, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udceb' in position 35: surrogates not allowed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 372, in scan_photos
    pool.starmap(photo_scanner, all)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
UnicodeEncodeError: 'utf-8' codec can't encode character '\udceb' in position 35: surrogates not allowed
2023-04-17 15:33:08,887 : directory_watcher.py : scan_photos : 390 : INFO : Added 2 photos
2023-04-17 15:33:26,934 : face_classify.py : train_faces : 251 : INFO : Before fitting
2023-04-17 15:33:38,012 : face_classify.py : train_faces : 255 : INFO : After fitting
2023-04-17 15:33:38,012 : face_classify.py : train_faces : 260 : INFO : Number of Cluster: 1944
2023-04-17 15:36:21,665 : api_util.py : get_search_term_examples : 178 : INFO : 93 possible ids
2023-04-17 15:36:21,665 : api_util.py : get_search_term_examples : 191 : INFO : Getting search terms for user 1
2023-04-17 15:36:21,729 : api_util.py : get_search_term_examples : 192 : INFO : Found 93 photos
```

## Please provide additional information:
- 💻 Operating system: Docker on a Ubuntu server 22.04 LTS
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: latest (?)
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:

```
# DO NOT EDIT
# The .env file has everything you need to edit.
# Run options:
# 1. Use prebuilt images (preferred method):
#   run cmd: docker-compose up -d
# 2. Build images on your own machine:
#   build cmd: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
#   run cmd: docker-compose up -d

version: "3.8"
services:
  proxy:
    image: reallibrephotos/librephotos-proxy:${tag}
    container_name: librephotos-proxy
    restart: unless-stopped
    volumes:
      - ${scanDirectory}:/data
      - ${data}/protected_media:/protected_media
    ports:
      - ${httpPort}:80
    depends_on:
      - backend
      - frontend

#  db:
#    image: postgres:13
#    container_name: db
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=${dbUser}
#      - POSTGRES_PASSWORD=${dbPass}
#      - POSTGRES_DB=${dbName}
#    volumes:
#      - ${data}/db:/var/lib/postgresql/data
#    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
#    healthcheck:
#      test: psql -U ${dbUser} -d ${dbName} -c "SELECT 1;"
#      interval: 5s
#      timeout: 5s
#      retries: 5

  frontend:
    image: reallibrephotos/librephotos-frontend:${tag}
    container_name: librephotos-frontend
    restart: unless-stopped

  backend:
    image: reallibrephotos/librephotos:${tag}
    container_name: librephotos-backend
    restart: unless-stopped
    volumes:
      - ${scanDirectory}:/data
      - ${data}/protected_media:/protected_media
      - ${data}/logs:/logs
      - ${data}/cache:/root/.cache
    environment:
      - SECRET_KEY=${shhhhKey:-}
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=${adminEmail:-}
      - ADMIN_USERNAME=${userName:-}
      - ADMIN_PASSWORD=${userPass:-}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=${dbHost}
      - DB_PORT=5432
      - REDIS_HOST=192.168.11.11
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${mapApiKey:-}
      - WEB_CONCURRENCY=${gunniWorkers:-1}
      - SKIP_PATTERNS=${skipPatterns:-}
      - ALLOW_UPLOAD=${allowUpload:-false}
      - CSRF_TRUSTED_ORIGINS=${csrfTrustedOrigins:-}
      - DEBUG=0
      - HEAVYWEIGHT_PROCESS=${HEAVYWEIGHT_PROCESS:-}
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy

#  redis:
#    image: redis:6
#    container_name: redis
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
#      interval: 5s
#      timeout: 5s
#      retries: 12


```

- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.):  ext4

**Comment by sickelap** [comment]
I suspect the filename or directory with weird characters. Can you try to narrow down to the actual path? Would be good to get the sample to reproduce this.

**Comment by Chacsam** [comment]
Hello,

It took me quite some time, but I have finally found the issue.
One of the sub-sub-folder was called "Noël"  (Christmas in French), the ë was the issue.

**Comment by Chacsam** [comment]
Noticed it's also an issue with those text caracters in filename (eg. café).
Might be a relevant improvement

**Comment by sickelap** [comment]
Huh!? Which French that is? I tried installing french layout and could not find character e with two dots :rofl:

**Comment by loulou91** [comment]
Same as #810 ??? 😉

**Comment by sickelap** [comment]
Could be, but that is supposed to be fixed.

**Comment by derneuere** [comment]
@Chacsam Could you look into the default encoding of your database? Maybe the default is not UTF-8 but something else.

**Comment by Chacsam** [comment]
Good morning,

Sorry I have removed Librephotos from my setup (mainly because I couldn't manage my pictures mounted in a NAS drive) in the meantime, cannot help you anymore.
Best
