### ISSUE TITLE
Public photo share failed

### ISSUE THREAD

**Issue by ghost** [LibrePhotos/librephotos#881]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files (error log pasted below)
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Loading public link forever:
![image](https://github.com/LibrePhotos/librephotos/assets/77554817/7c6df935-fda1-48f2-9745-519a968e05f0)

## 🔁 How can we reproduce it:
Share some photos (I have 100+ shared), use the www.example.com/user/user_name link to load the shared photos

## Please provide additional information:
- 💻 Operating system: Arch
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: reallibrephotos/librephotos:latest as of date of written
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: reallibrephotos/librephotos:latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): No

```
Internal Server Error: /api/albums/date/list/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/api/views/albums.py", line 545, in list
    serializer = IncompleteAlbumDateSerializer(self.get_queryset(), many=True)
                                               ^^^^^^^^^^^^^^^^^^^
  File "/code/api/views/albums.py", line 526, in get_queryset
    qs.annotate(
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/aggregates.py", line 65, in resolve_expression
    c.filter = c.filter and c.filter.resolve_expression(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query_utils.py", line 87, in resolve_expression
    clause, joins = query._add_q(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1533, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1448, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1275, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/fields/__init__.py", line 2057, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x69542cf1f690>.
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/albums/thing/list/
Unauthorized: /api/albums/place/list/
Unauthorized: /api/persons/
Unauthorized: /api/albums/user/list/
```

**Comment by derneuere** [comment]
Duplicate of #880

**Comment by gabriel-farache** [comment]
Sorry to comment on a closed issue but I just had the same error:
```
backend  | Internal Server Error: /api/albums/date/list/
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
backend  |     return int(value)
backend  |            ^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/contrib/auth/models.py", line 437, in __int__
backend  |     raise TypeError(
backend  | TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?
backend  | 
backend  | 
backend  | The above exception was the direct cause of the following exception:
backend  | 
backend  | 
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
backend  |     response = get_response(request)
backend  |                ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
backend  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
backend  |     return view_func(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/rest_framework/viewsets.py", line 125, in view
backend  |     return self.dispatch(request, *args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 509, in dispatch
backend  |     response = self.handle_exception(exc)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 469, in handle_exception
backend  |     self.raise_uncaught_exception(exc)
backend  |   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 506, in dispatch
backend  |     response = handler(request, *args, **kwargs)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/api/views/albums.py", line 535, in list
backend  |     serializer = IncompleteAlbumDateSerializer(self.get_queryset(), many=True)
backend  |                                                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/api/views/albums.py", line 516, in get_queryset
backend  |     qs.annotate(
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1590, in annotate
backend  |     return self._annotate(args, kwargs, select=True)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1638, in _annotate
backend  |     clone.query.add_annotation(
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1090, in add_annotation
backend  |     annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
backend  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/aggregates.py", line 65, in resolve_expression
backend  |     c.filter = c.filter and c.filter.resolve_expression(
backend  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/query_utils.py", line 87, in resolve_expression
backend  |     clause, joins = query._add_q(
backend  |                     ^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1533, in _add_q
backend  |     child_clause, needed_inner = self.build_filter(
backend  |                                  ^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1448, in build_filter
backend  |     condition = self.build_lookup(lookups, col, value)
backend  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/query.py", line 1275, in build_lookup
backend  |     lookup = lookup_class(lhs, rhs)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/lookups.py", line 27, in __init__
backend  |     self.rhs = self.get_prep_lookup()
backend  |                ^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
backend  |     self.rhs = target_field.get_prep_value(self.rhs)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/dist-packages/django/db/models/fields/__init__.py", line 2057, in get_prep_value
backend  |     raise e.__class__(
backend  | TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7f6513a6d0>.
```
I am using `reallibrephotos/librephotos:latest`, was the PR merged?
