### ISSUE TITLE
 Test setup fails on 0027 migration.

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#898]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Migration for Person model breaks test environment setup. Test setup faiils on 0027 migration. Reported by sickelap.
This also seems to break migration in general, but only for new systems.

[command_migrate.log](https://github.com/LibrePhotos/librephotos/files/11860585/command_migrate.log)
[rqworker.log](https://github.com/LibrePhotos/librephotos/files/11860586/rqworker.log)

## 🔁 How can we reproduce it:

Start a new system from scratch with the dev image.

**Comment by EvilDrW** [comment]
I'm seeing problems on the 0027 migration after upgrading the docker images... not sure if it's related to what you have here or not.  I couldn't find anything that looked similar in the issues.  Should I open a new issue or is this related to what's here?

>   Applying api.0027_rename_unknown_person...Traceback (most recent call last):
  File "/code/manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/code/api/migrations/0027_rename_unknown_person.py", line 20, in migrate_unknown
    if unknown_person.kind != KIND_UNKNOWN:
       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'unknown_person' where it is not associated with a value

**Comment by derneuere** [comment]
Sounds like a new problem! Please open up a new issue :)
