### ISSUE TITLE
Search return blank page

### ISSUE THREAD

**Issue by zodiacg** [LibrePhotos/librephotos#913]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

Search anything in the search bar and the page will become blank.

Console log from the browser:
```
Data provided is grouped, please include the groupByDate prop
a @ index.js:65
Wi @ react-dom.production.min.js:147
js @ react-dom.production.min.js:198
kl @ react-dom.production.min.js:292
bu @ react-dom.production.min.js:280
gu @ react-dom.production.min.js:280
vu @ react-dom.production.min.js:280
lu @ react-dom.production.min.js:273
Ho @ react-dom.production.min.js:127
(匿名) @ react-dom.production.min.js:267
XMLHttpRequest.send(异步)
(匿名) @ xhr.js:220
e.exports @ xhr.js:16
e.exports @ dispatchRequest.js:56
Promise.then(异步)
d.request @ Axios.js:89
r.forEach.d.<computed> @ Axios.js:131
(匿名) @ bind.js:9
(匿名) @ searchActions.js:16
(匿名) @ index.js:16
P @ CustomSearch.tsx:140
onItemSubmit @ CustomSearch.tsx:185
onItemSelect @ Autocomplete.tsx:154
t.createElement.onMouseDown @ SelectItems.tsx:64
Le @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(匿名) @ react-dom.production.min.js:55
Nr @ react-dom.production.min.js:105
Rr @ react-dom.production.min.js:106
(匿名) @ react-dom.production.min.js:117
uu @ react-dom.production.min.js:274
ze @ react-dom.production.min.js:52
Wr @ react-dom.production.min.js:109
qt @ react-dom.production.min.js:74
Vt @ react-dom.production.min.js:73
202react-dom.production.min.js:189  TypeError: Cannot read properties of undefined (reading 'includes')
    at Tile.js:31:6
    at Sa (react-dom.production.min.js:167:137)
    at Ps (react-dom.production.min.js:197:258)
    at Ss (react-dom.production.min.js:195:204)
    at ks (react-dom.production.min.js:194:176)
    at kl (react-dom.production.min.js:297:71)
    at bu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
fs @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Zi @ react-dom.production.min.js:144
_l @ react-dom.production.min.js:262
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(匿名) @ react-dom.production.min.js:283
wu @ react-dom.production.min.js:281
lu @ react-dom.production.min.js:273
Ho @ react-dom.production.min.js:127
(匿名) @ react-dom.production.min.js:267
XMLHttpRequest.send(异步)
(匿名) @ xhr.js:220
e.exports @ xhr.js:16
e.exports @ dispatchRequest.js:56
Promise.then(异步)
d.request @ Axios.js:89
r.forEach.d.<computed> @ Axios.js:131
(匿名) @ bind.js:9
(匿名) @ searchActions.js:16
(匿名) @ index.js:16
P @ CustomSearch.tsx:140
onItemSubmit @ CustomSearch.tsx:185
onItemSelect @ Autocomplete.tsx:154
t.createElement.onMouseDown @ SelectItems.tsx:64
Le @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(匿名) @ react-dom.production.min.js:55
Nr @ react-dom.production.min.js:105
Rr @ react-dom.production.min.js:106
(匿名) @ react-dom.production.min.js:117
uu @ react-dom.production.min.js:274
ze @ react-dom.production.min.js:52
Wr @ react-dom.production.min.js:109
qt @ react-dom.production.min.js:74
Vt @ react-dom.production.min.js:73
Tile.js:31  Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at Tile.js:31:6
    at Sa (react-dom.production.min.js:167:137)
    at Ps (react-dom.production.min.js:197:258)
    at Ss (react-dom.production.min.js:195:204)
    at ks (react-dom.production.min.js:194:176)
    at kl (react-dom.production.min.js:297:71)
    at bu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
(匿名) @ Tile.js:31
Sa @ react-dom.production.min.js:167
Ps @ react-dom.production.min.js:197
Ss @ react-dom.production.min.js:195
ks @ react-dom.production.min.js:194
kl @ react-dom.production.min.js:297
bu @ react-dom.production.min.js:280
gu @ react-dom.production.min.js:280
vu @ react-dom.production.min.js:280
iu @ react-dom.production.min.js:271
lu @ react-dom.production.min.js:273
Ho @ react-dom.production.min.js:127
(匿名) @ react-dom.production.min.js:267
XMLHttpRequest.send(异步)
(匿名) @ xhr.js:220
e.exports @ xhr.js:16
e.exports @ dispatchRequest.js:56
Promise.then(异步)
d.request @ Axios.js:89
r.forEach.d.<computed> @ Axios.js:131
(匿名) @ bind.js:9
(匿名) @ searchActions.js:16
(匿名) @ index.js:16
P @ CustomSearch.tsx:140
onItemSubmit @ CustomSearch.tsx:185
onItemSelect @ Autocomplete.tsx:154
t.createElement.onMouseDown @ SelectItems.tsx:64
Le @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(匿名) @ react-dom.production.min.js:55
Nr @ react-dom.production.min.js:105
Rr @ react-dom.production.min.js:106
(匿名) @ react-dom.production.min.js:117
uu @ react-dom.production.min.js:274
ze @ react-dom.production.min.js:52
Wr @ react-dom.production.min.js:109
qt @ react-dom.production.min.js:74
Vt @ react-dom.production.min.js:73
```

![image](https://github.com/LibrePhotos/librephotos/assets/910023/54af2f05-68bf-4665-9664-4d1a25848297)

## 🔁 How can we reproduce it:

Search anything in the search bar.

## Please provide additional information:
- 💻 Operating system: Ubuntu 22.04
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: 2023w26.1
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.):  Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):  N/A

**Comment by derneuere** [comment]
This issue only occured when semantic search was used. I pushed a fix. It will be in the next release or currently on dev :)
