### ISSUE TITLE
Unable to enter 'first time setup', unable to set usename and password

### ISSUE THREAD

**Issue by husthyx** [LibrePhotos/librephotos#915]
# 🐛 Bug Report

* [*  ] 📁 I've Included a ZIP file containing my librephotos `log` 
*waiting for server to start....2023-07-07 09:06:35.583 CST [280] LOG:  starting PostgreSQL 13.11 (Ubuntu 13.11-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
2023-07-07 09:06:36.486 CST [280] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
.2023-07-07 09:06:36.628 CST [283] LOG:  database system was shut down at 2023-07-07 09:06:02 CST
2023-07-07 09:06:36.666 CST [280] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE

/usr/local/bin/postgres-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2023-07-07 09:06:57.021 CST [280] LOG:  received fast shutdown request
waiting for server to shut down....2023-07-07 09:06:57.050 CST [280] LOG:  aborting any active transactions
2023-07-07 09:06:57.053 CST [280] LOG:  background worker "logical replication launcher" (PID 289) exited with exit code 1
2023-07-07 09:06:57.053 CST [284] LOG:  shutting down
2023-07-07 09:06:57.476 CST [280] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

* [ ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I reinstall Docker realibrepotots/singleton，Unable to enter 'first time setup', unable to set usename and password。

## Please provide additional information:
💻 Operating system: unraid 6.11.5
⚙ Architecture (x86 or ARM): x86
🔢 Librephotos version: [2023w26]
📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
🐋 If Docker or Kubernets, provide docker-compose image tag: [2023w20]
📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local file system
☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by madhusudhanarya** [comment]
I too faced same issue/error while setting up LibrePhotos on my Unraid server running 6.11.5 version.

If it helps the developer, below is the error/traceback causing the issue. 

`root@unraid:/mnt/user/Appdata/Librephotos/logs# more gunicorn_django.log 
[2023-07-09 19:27:28 +0530] [346] [INFO] Starting gunicorn 20.1.0
[2023-07-09 19:27:28 +0530] [346] [INFO] Listening at: http://127.0.0.1:8001 (346)
[2023-07-09 19:27:28 +0530] [346] [INFO] Using worker: gevent
[2023-07-09 19:27:28 +0530] [348] [INFO] Booting worker with pid: 348
[2023-07-09 19:27:28 +0530] [349] [INFO] Booting worker with pid: 349
use SECRET_KEY from env
use SECRET_KEY from env
[2023-07-09 13:58:56 +0000] [348] [ERROR] Error handling request /api/firsttimesetup/
Traceback (most recent call last):
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/ownphotos/urls.py", line 29, in <module>
    from api.views import (
  File "/usr/lib/librephotos/backend/api/views/dataviz.py", line 12, in <module>
    from api.face_classify import cluster_faces
  File "/usr/lib/librephotos/backend/api/face_classify.py", line 11, in <module>
    from hdbscan import HDBSCAN
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 40, in <module>
    FAST_METRICS = KDTree.valid_metrics + BallTree.valid_metrics + ["cosine", "arccos"]
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/librephotos/backend/api/middleware.py", line 7, in __call__
    response = self.get_response(request)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
    callback = resolver.resolve_error_handler(500)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 729, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/ownphotos/urls.py", line 29, in <module>
    from api.views import (
  File "/usr/lib/librephotos/backend/api/views/dataviz.py", line 12, in <module>
    from api.face_classify import cluster_faces
  File "/usr/lib/librephotos/backend/api/face_classify.py", line 11, in <module>
    from hdbscan import HDBSCAN
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 40, in <module>
    FAST_METRICS = KDTree.valid_metrics + BallTree.valid_metrics + ["cosine", "arccos"]
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'builtin_function_or_method'`

**Comment by derneuere** [comment]
I pushed a fix for this bug yesterday. Pull the new image and let me know how it goes :)

**Comment by joao-matos** [comment]
Same. Fresh setup.
raspberry pi 3B.
latest dietpi.
docker.
followed strict instructions.
on opening the url for the first time, it goes to the login page instead of the wizard.
