### ISSUE TITLE
Error on 0027_rename_unknown_person

### ISSUE THREAD

**Issue by EvilDrW** [LibrePhotos/librephotos#984]
* [x ] 📁 I've Included a ZIP file containing my librephotos `log` files: [logs.tar.gz](https://github.com/LibrePhotos/librephotos/files/12285656/logs.tar.gz)

* [ x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I asked about this in #898 and was requested to open a new issue.  After pulling new docker images (mine were ~2 years old), I'm getting errors on 

> 22:40:00 [Job 63c8a42b-3a79-45ce-b2e4-731224036428]: exception raised while executing (api.apps.build_index)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column api_user.confidence_person does not exist
LINE 1: ..._user"."scan_directory", "api_user"."confidence", "api_user"...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/rq/worker.py", line 1418, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rq/job.py", line 1225, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rq/job.py", line 1262, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/api/apps.py", line 18, in build_index
    for user in User.objects.all():
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column api_user.confidence_person does not exist
LINE 1: ..._user"."scan_directory", "api_user"."confidence", "api_user"...

## 🔁 How can we reproduce it:
Not sure.  All that I did was to pull new docker images and restart my installation using docker-compose.

Operating system is Ubuntu 18.04.  Arch is x86.  Running librephotos on docker via docker-compose.  Images mount is from a local file system (ext4).

**Comment by derneuere** [comment]
This error just states, that the migration was not done. There should be an error above that, which could tell me, what actually went wrong :)

EDIT: command_migrate indicates that the migration is still running, maybe it just takes a while?
EDIT2: hmm, should be actually pretty fast. is there maybe another error in the console?

**Comment by EvilDrW** [comment]
I attached a tarball of the logs, does it not have what you are looking
for?  Is there something I missed in the instructions to increase the
logging level or something?

**Comment by derneuere** [comment]
Sadly not. There should be an error in command_migrate.log, but there isn't. Start up the containers with docker-compose up without the -d. There should be a new error when it's migrating, which would help me out tracking down the error.

**Comment by EvilDrW** [comment]
Hopefully the attached is what you're looking for?
[librephotos.log](https://github.com/LibrePhotos/librephotos/files/12414083/librephotos.log)

**Comment by derneuere** [comment]
Pushed a fix :) It is available in the dev image and will be in the next latest release.
